import AsyncStorage from '@react-native-async-storage/async-storage';
import { getAllExercises, insertExercise } from './database';

const SEEDED_KEY = '@volyume_exercises_seeded_v6';

// Anatomical subregion tags — used by planEngine v2 to enforce balanced muscle coverage.
// Muscles not listed here (e.g. biceps, forearms) do not have enforced subregion requirements.
const SUBREGION_MAP = {
  // Back — vertical pull vs horizontal row
  'Lat Pulldown (Wide Grip)':        'vertical_pull',
  'Lat Pulldown (Close Grip)':       'vertical_pull',
  'Lat Pulldown (Neutral Grip)':     'vertical_pull',
  'Pull-Up':                         'vertical_pull',
  'Weighted Pull-Up':                'vertical_pull',
  'Chin-Up':                         'vertical_pull',
  'Neutral Grip Pull-Up':            'vertical_pull',
  'Assisted Pull-Up':                'vertical_pull',
  'Single-Arm Lat Pulldown':         'vertical_pull',
  'Cable Lat Pullover':              'vertical_pull',
  'Cable Straight-Arm Pulldown':     'vertical_pull',
  'Barbell Row (Bent Over)':         'horizontal_row',
  'Dumbbell Row':                    'horizontal_row',
  'T-Bar Row':                       'horizontal_row',
  'Seated Cable Row':                'horizontal_row',
  'Machine Row (Chest Supported)':   'horizontal_row',
  'Landmine Row':                    'horizontal_row',
  'Pendlay Row':                     'horizontal_row',
  'Inverted Row':                    'horizontal_row',
  'Cable High Row':                  'horizontal_row',
  'Single-Arm Cable Row':            'horizontal_row',
  'Meadows Row':                     'horizontal_row',
  'Kroc Row':                        'horizontal_row',
  'Seal Row':                        'horizontal_row',
  'Chest-Supported Row (Dumbbell)':  'horizontal_row',
  'Seated Machine Row (Wide)':       'horizontal_row',
  'Chest-Supported T-Bar Row':       'horizontal_row',
  'Helms Row':                       'horizontal_row',
  'Barbell Row (Supinated)':         'horizontal_row',
  'Conventional Deadlift':           'lower_lat',
  'Sumo Deadlift':                   'lower_lat',
  'Rack Pull':                       'lower_lat',
  'Trap Bar Deadlift':               'lower_lat',
  'Snatch Grip Deadlift':            'lower_lat',
  'Deficit Deadlift':                'lower_lat',
  'Romanian Deadlift (Barbell)':     'lower_lat',
  'Hyperextension (Back Extension)': 'lower_lat',
  'Reverse Hyperextension':          'lower_lat',
  'Romanian Deadlift (Single-Leg)':  'lower_lat',
  'Stiff-Leg Deadlift (Dumbbell)':   'lower_lat',
  'Back Extension (Weighted)':       'lower_lat',

  // Back — additional rows
  'Cable Row (Wide Grip)':           'horizontal_row',
  'Single-Arm Dumbbell Row (Supported)': 'horizontal_row',
  'Banded Row':                      'horizontal_row',
  'Machine Row (Hammer Strength)':   'horizontal_row',
  'TRX Row':                         'horizontal_row',

  // Chest — incline vs flat vs decline
  'Barbell Bench Press':             'flat',
  'Dumbbell Bench Press':            'flat',
  'Machine Chest Press':             'flat',
  'Cable Fly (Neutral)':             'flat',
  'Cable Crossover (High to Low)':   'flat',
  'Dumbbell Fly':                    'flat',
  'Pec Deck (Machine Fly)':          'flat',
  'Smith Machine Bench Press':       'flat',
  'Cable Fly (Chest Height)':        'flat',
  'Svend Press':                     'flat',
  'Wide-Grip Push-Up':               'flat',
  'Push-Up':                         'flat',
  'Ring Push-Up':                    'flat',
  'Band Push-Up':                    'flat',
  'Incline Barbell Bench Press':     'incline',
  'Incline Dumbbell Press':          'incline',
  'Incline Dumbbell Fly':            'incline',
  'Incline Machine Press':           'incline',
  'Cable Fly (Low to High)':         'incline',
  'Landmine Press':                  'incline',
  'Incline Smith Machine Press':     'incline',
  'Incline Cable Fly':               'incline',
  'Low Cable Fly':                   'incline',
  'High Cable Fly':                  'flat',
  'Decline Barbell Bench Press':     'decline',
  'Decline Dumbbell Press':          'decline',
  'Weighted Dips (Chest)':           'decline',
  'Decline Dumbbell Fly':            'decline',
  'Decline Push-Up':                 'decline',
  'Decline Machine Press':           'decline',
  'Reverse-Grip Bench Press':        'flat',
  'Dumbbell Squeeze Press':          'flat',
  'Cable Fly (Low to High) (Alt)':   'incline',

  // Delts — overhead press (front) vs lateral raise (side) vs face pull / fly (rear)
  'Barbell Overhead Press':          'overhead_press',
  'Dumbbell Shoulder Press':         'overhead_press',
  'Arnold Press':                    'overhead_press',
  'Machine Shoulder Press':          'overhead_press',
  'Seated Dumbbell Press':           'overhead_press',
  'Z-Press':                         'overhead_press',
  'Push Press':                      'overhead_press',
  'Viking Press':                    'overhead_press',
  'Dumbbell Lateral Raise':          'lateral_raise',
  'Cable Lateral Raise':             'lateral_raise',
  'Machine Lateral Raise':           'lateral_raise',
  'Leaning Cable Lateral Raise':     'lateral_raise',
  'Plate Lateral Raise':             'lateral_raise',
  'Leaning Lateral Raise':           'lateral_raise',
  'Landmine Lateral Raise':          'lateral_raise',
  'Band Lateral Raise':              'lateral_raise',
  'Seated Lateral Raise':            'lateral_raise',
  'Upright Row':                     'lateral_raise',
  'Dumbbell Rear Delt Fly':          'horiz_abduction',
  'Cable Rear Delt Fly':             'horiz_abduction',
  'Machine Rear Delt Fly':           'horiz_abduction',
  'Reverse Pec Deck':                'horiz_abduction',
  'Cable Y-Raise (Prone)':           'horiz_abduction',
  'Dumbbell Side-Lying Rear Delt':   'horiz_abduction',
  'W-Raise':                         'horiz_abduction',
  'YTW':                             'horiz_abduction',
  'Cable Face Pull':                 'face_pull',
  'Face Pull':                       'face_pull',
  'Face Pull (Rope)':                'face_pull',
  'Band Face Pull':                  'face_pull',
  'Lying Rear Delt Row':             'horiz_abduction',
  'Prone Incline Y-Raise':           'horiz_abduction',
  'Prone Incline T-Raise':           'horiz_abduction',
  'Seated Rear Delt Machine':        'horiz_abduction',
  'Bent-Over Cable Rear Delt Fly':   'horiz_abduction',
  'Cable Face Pull (Rope)':          'face_pull',

  // Hamstrings — hip extension vs knee flexion
  'Romanian Deadlift':               'hip_extension',
  'Stiff-Leg Deadlift':              'hip_extension',
  'Good Morning':                    'hip_extension',
  'Single-Leg Romanian Deadlift':    'hip_extension',
  'Single-Leg Romanian Deadlift (DB)': 'hip_extension',
  'B-Stance Romanian Deadlift':      'hip_extension',
  'Dumbbell Single-Leg RDL':         'hip_extension',
  'Cable Stiff-Leg Deadlift':        'hip_extension',
  'Nordic Hamstring Curl':           'knee_flexion',
  'Prone Leg Curl':                  'knee_flexion',
  'Nordic Curl':                     'knee_flexion',
  'Lying Leg Curl':                  'knee_flexion',
  'Seated Leg Curl':                 'knee_flexion',
  'Standing Leg Curl':               'knee_flexion',
  'Swiss Ball Leg Curl':             'knee_flexion',
  'Glute Ham Raise':                 'knee_flexion',
  'Leg Curl (Cable)':                'knee_flexion',

  // Triceps — overhead (long head) vs pushdown
  'EZ Bar Skull Crusher':            'overhead',
  'Dumbbell Skull Crusher':          'overhead',
  'Decline Skull Crusher':           'overhead',
  'Cable Overhead Tricep Extension': 'overhead',
  'Close-Grip Floor Press':          'pushdown',
  'Reverse Grip Cable Pushdown':     'pushdown',
  'Overhead Dumbbell Extension':     'overhead',
  'Dumbbell Overhead Tricep Extension': 'overhead',
  'Overhead Cable Tricep Extension': 'overhead',
  'JM Press':                        'pushdown',
  'Board Press':                     'pushdown',
  'Tricep Pushdown (Bar)':           'pushdown',
  'Tricep Pushdown (Rope)':          'pushdown',
  'Cable Pushdown (Straight Bar)':   'pushdown',
  'Rope Pushdown':                   'pushdown',
  'Machine Tricep Extension':        'pushdown',
  'Close-Grip Bench Press':          'pushdown',
  'Bench Dip':                       'pushdown',
  'Diamond Push-Up':                 'pushdown',
  'Single Arm Cable Extension':      'pushdown',
  'Tate Press':                      'pushdown',
  'Tricep Kickback':                 'pushdown',
  'Weighted Dips (Triceps)':         'pushdown',
  'Lying Tricep Extension':          'overhead',

  // Calves — gastrocnemius vs soleus
  'Standing Calf Raise (Machine)':   'gastro',
  'Standing Calf Raise (Barbell)':   'gastro',
  'Leg Press Calf Raise':            'gastro',
  'Smith Machine Calf Raise':        'gastro',
  'Donkey Calf Raise':               'gastro',
  'Dumbbell Calf Raise (Standing)':  'gastro',
  'Single-Leg Calf Raise (Bodyweight)': 'gastro',
  'Calf Raise on Steps':             'gastro',
  'Seated Calf Raise':               'soleus',
  'Seated Machine Calf Raise':       'soleus',
  'Seated Dumbbell Calf Raise':      'soleus',

  // Calves — additional gastro entries
  'Single-Leg Calf Raise (Dumbbell)':  'gastro',
  'Calf Raise on Leg Press Sled':      'gastro',
  'Standing Calf Raise (Bodyweight)':  'gastro',
  'Jump Rope':                         'gastro',

  // Abs — flexion vs anti-extension vs rotation
  'Cable Crunch':                    'flexion',
  'Decline Crunch':                  'flexion',
  'Machine Crunch':                  'flexion',
  'Hanging Knee Raise':              'flexion',
  'Hanging Leg Raise':               'flexion',
  'Reverse Crunch':                  'flexion',
  'Crunch':                          'flexion',
  'Bicycle Crunch':                  'flexion',
  'Leg Raise':                       'flexion',
  'Sit-Up':                          'flexion',
  'V-Up':                            'flexion',
  'Leg Raise (Flat Bench)':          'flexion',
  'Dragon Flag':                     'anti_extension',
  'Ab Rollout':                      'anti_extension',
  'Ab Wheel Rollout':                'anti_extension',
  'Plank':                           'anti_extension',
  'Dead Bug':                        'anti_extension',
  'Pallof Press':                    'anti_extension',
  'Side Plank':                      'anti_extension',
  'Hollow Body Hold':                'anti_extension',
  'Stir the Pot':                    'anti_extension',
  'Russian Twist':                   'rotation',
  'Cable Woodchop':                  'rotation',
  'Landmine Twist':                  'rotation',
  'Landmine Rotation':               'rotation',
};

// [name, primaryMuscle, secondaryMuscles, equipment, movementPattern, isCompound, minReps, maxReps, fatigueCost, sfr]
// fatigueCost: 1-10 (10 = very high systemic fatigue, e.g. deadlift)
// sfr: stimulus-to-fatigue ratio 1-10 (10 = excellent stimulus with low fatigue)
const RAW = [
  // ─── CHEST ───────────────────────────────────────────────────────────────────
  ['Barbell Bench Press',           'chest', ['triceps', 'front_delts'],   'barbell',      'push',      true,  4, 8,   4, 3],
  ['Incline Barbell Bench Press',   'chest', ['triceps', 'front_delts'],   'barbell',      'push',      true,  5, 10,  4, 3],
  ['Decline Barbell Bench Press',   'chest', ['triceps'],                  'barbell',      'push',      true,  6, 10,  3, 3],
  ['Dumbbell Bench Press',          'chest', ['triceps', 'front_delts'],   'dumbbell',     'push',      true,  6, 12,  3, 4],
  ['Incline Dumbbell Press',        'chest', ['triceps', 'front_delts'],   'dumbbell',     'push',      true,  8, 15,  3, 4],
  ['Decline Dumbbell Press',        'chest', ['triceps'],                  'dumbbell',     'push',      true,  8, 15,  3, 4],
  ['Cable Fly (Low to High)',       'chest', [],                           'cable',        'isolation', false, 12, 20, 2, 5],
  ['Cable Crossover (High to Low)', 'chest', [],                           'cable',        'isolation', false, 12, 20, 2, 5],
  ['Dumbbell Fly',                  'chest', [],                           'dumbbell',     'isolation', false, 10, 15, 2, 4],
  ['Incline Dumbbell Fly',          'chest', [],                           'dumbbell',     'isolation', false, 10, 15, 2, 4],
  ['Decline Dumbbell Fly',          'chest', [],                           'dumbbell',     'isolation', false, 10, 15, 2, 4],
  ['Pec Deck (Machine Fly)',        'chest', [],                           'machine',      'isolation', false, 12, 20, 2, 5],
  ['Machine Chest Press',           'chest', ['triceps', 'front_delts'],   'machine',      'push',      true,  8, 15,  3, 4],
  ['Incline Machine Press',         'chest', ['triceps', 'front_delts'],   'machine',      'push',      true,  8, 15,  3, 4],
  ['Decline Machine Press',         'chest', ['triceps'],                  'machine',      'push',      true,  8, 15,  3, 4],
  ['Weighted Dips (Chest)',         'chest', ['triceps', 'front_delts'],   'bodyweight',   'push',      true,  6, 15,  4, 3],
  ['Push-Up',                       'chest', ['triceps', 'front_delts'],   'bodyweight',   'push',      true,  10, 20, 2, 3],
  ['Wide-Grip Push-Up',             'chest', ['triceps', 'front_delts'],   'bodyweight',   'push',      true,  10, 20, 2, 3],
  ['Decline Push-Up',               'chest', ['triceps', 'front_delts'],   'bodyweight',   'push',      true,  10, 20, 2, 3],
  ['Ring Push-Up',                  'chest', ['triceps', 'front_delts'],   'bodyweight',   'push',      true,  8, 15,  3, 4],
  ['Landmine Press',                'chest', ['front_delts'],              'barbell',      'push',      true,  8, 15,  3, 4],
  ['Smith Machine Bench Press',     'chest', ['triceps', 'front_delts'],   'smith_machine','push',      true,  6, 12,  3, 3],
  ['Incline Smith Machine Press',   'chest', ['triceps', 'front_delts'],   'smith_machine','push',      true,  8, 15,  3, 4],
  ['Cable Fly (Neutral)',           'chest', [],                           'cable',        'isolation', false, 12, 20, 2, 5],
  ['Cable Fly (Chest Height)',      'chest', [],                           'cable',        'isolation', false, 12, 20, 2, 5],
  ['High Cable Fly',                'chest', [],                           'cable',        'isolation', false, 12, 20, 2, 5],
  ['Low Cable Fly',                 'chest', [],                           'cable',        'isolation', false, 12, 20, 2, 5],
  ['Incline Cable Fly',             'chest', [],                           'cable',        'isolation', false, 12, 20, 2, 5],
  ['Svend Press',                   'chest', [],                           'barbell',      'isolation', false, 15, 25, 2, 4],
  ['Dumbbell Pullover',             'chest', ['back'],                     'dumbbell',     'isolation', false, 10, 15, 2, 4],
  ['Band Push-Up',                  'chest', ['triceps', 'front_delts'],   'bodyweight',   'push',      true,  10, 20, 2, 4],
  ['Hammer Strength Chest Press',   'chest', ['triceps', 'front_delts'],   'machine',      'push',      true,  8, 15,  3, 4],
  ['Reverse-Grip Bench Press',      'chest', ['triceps', 'front_delts'],   'barbell',      'push',      true,  6, 12,  3, 4],
  ['Dumbbell Squeeze Press',        'chest', ['triceps'],                  'dumbbell',     'push',      true,  8, 15,  2, 4],
  ['Cable Fly (Low to High)',       'chest', [],                           'cable',        'isolation', false, 12, 20, 2, 5],
  ['Cable Fly (High to Low)',       'chest', [],                           'cable',        'isolation', false, 12, 20, 2, 5],
  ['Dumbbell Pullover (Chest)',     'chest', ['back'],                     'dumbbell',     'isolation', false, 10, 15, 2, 4],

  // ─── BACK ────────────────────────────────────────────────────────────────────
  ['Barbell Row (Bent Over)',       'back', ['biceps', 'rear_delts'],      'barbell',      'pull',      true,  5, 10,  4, 3],
  ['Barbell Row (Supinated)',       'back', ['biceps'],                    'barbell',      'pull',      true,  6, 10,  4, 4],
  ['Dumbbell Row',                  'back', ['biceps'],                    'dumbbell',     'pull',      true,  8, 15,  3, 4],
  ['T-Bar Row',                     'back', ['biceps'],                    'barbell',      'pull',      true,  6, 12,  4, 3],
  ['Chest-Supported T-Bar Row',     'back', ['biceps'],                    'barbell',      'pull',      true,  8, 15,  3, 5],
  ['Seated Cable Row',              'back', ['biceps'],                    'cable',        'pull',      true,  10, 15, 3, 4],
  ['Lat Pulldown (Wide Grip)',      'back', ['biceps'],                    'cable',        'pull',      true,  8, 15,  3, 4],
  ['Lat Pulldown (Close Grip)',     'back', ['biceps'],                    'cable',        'pull',      true,  8, 15,  3, 4],
  ['Lat Pulldown (Neutral Grip)',   'back', ['biceps'],                    'cable',        'pull',      true,  8, 15,  3, 4],
  ['Pull-Up',                       'back', ['biceps'],                    'bodyweight',   'pull',      true,  5, 15,  3, 4],
  ['Weighted Pull-Up',              'back', ['biceps'],                    'bodyweight',   'pull',      true,  4, 10,  4, 4],
  ['Chin-Up',                       'back', ['biceps'],                    'bodyweight',   'pull',      true,  5, 15,  3, 4],
  ['Neutral Grip Pull-Up',          'back', ['biceps'],                    'bodyweight',   'pull',      true,  5, 15,  3, 4],
  ['Assisted Pull-Up',              'back', ['biceps'],                    'machine',      'pull',      true,  8, 15,  3, 4],
  ['Machine Row (Chest Supported)', 'back', ['biceps'],                    'machine',      'pull',      true,  10, 15, 3, 4],
  ['Cable Straight-Arm Pulldown',   'back', [],                            'cable',        'pull',      false, 12, 20, 2, 5],
  ['Landmine Row',                  'back', ['biceps'],                    'barbell',      'pull',      true,  8, 15,  3, 4],
  ['Conventional Deadlift',         'back', ['quads', 'glutes', 'hamstrings'], 'barbell', 'hinge',     true,  3, 8,   5, 3],
  ['Sumo Deadlift',                 'back', ['quads', 'glutes', 'hamstrings'], 'barbell', 'hinge',     true,  3, 8,   5, 3],
  ['Rack Pull',                     'back', ['glutes'],                    'barbell',      'hinge',     true,  3, 8,   4, 3],
  ['Snatch Grip Deadlift',          'back', ['glutes', 'hamstrings'],      'barbell',      'hinge',     true,  3, 6,   5, 3],
  ['Deficit Deadlift',              'back', ['quads', 'glutes', 'hamstrings'], 'barbell', 'hinge',     true,  3, 6,   5, 3],
  ['Cable High Row',                'back', ['biceps'],                    'cable',        'pull',      true,  10, 15, 2, 4],
  ['Single-Arm Cable Row',          'back', ['biceps'],                    'cable',        'pull',      true,  10, 15, 3, 4],
  ['Trap Bar Deadlift',             'back', ['quads', 'glutes', 'hamstrings'], 'barbell', 'hinge',     true,  4, 8,   5, 4],
  ['Pendlay Row',                   'back', ['biceps'],                    'barbell',      'pull',      true,  5, 8,   4, 4],
  ['Inverted Row',                  'back', ['biceps'],                    'bodyweight',   'pull',      true,  8, 15,  2, 4],
  ['Cable Lat Pullover',            'back', [],                            'cable',        'pull',      false, 12, 20, 2, 5],
  ['Single-Arm Lat Pulldown',       'back', ['biceps'],                    'cable',        'pull',      true,  10, 15, 3, 4],
  ['Meadows Row',                   'back', ['biceps'],                    'barbell',      'pull',      true,  8, 15,  3, 4],
  ['Kroc Row',                      'back', ['biceps'],                    'dumbbell',     'pull',      true,  15, 25, 3, 4],
  ['Seal Row',                      'back', ['biceps'],                    'barbell',      'pull',      true,  6, 12,  3, 5],
  ['Chest-Supported Row (Dumbbell)','back', ['biceps'],                    'dumbbell',     'pull',      true,  8, 15,  3, 5],
  ['Seated Machine Row (Wide)',      'back', ['biceps'],                   'machine',      'pull',      true,  10, 15, 3, 4],
  ['Face Pull (Rope)',              'back', ['rear_delts', 'traps'],       'cable',        'pull',      false, 15, 25, 2, 5],
  ['Helms Row',                     'back', ['biceps'],                    'dumbbell',     'pull',      true,  8, 15,  3, 5],
  ['Hyperextension (Back Extension)','back',['glutes', 'hamstrings'],      'machine',      'hinge',     true,  10, 20, 2, 4],
  ['Good Morning (Barbell)',        'back', ['hamstrings', 'glutes'],      'barbell',      'hinge',     true,  8, 15,  4, 3],
  ['Reverse Hyperextension',        'back', ['glutes', 'hamstrings'],      'machine',      'hinge',     true,  12, 20, 2, 5],
  ['Chest-Supported Row',          'back', ['biceps'],                     'dumbbell',     'pull',      true,  8, 15,  3, 5],
  ['Cable Row (Wide Grip)',         'back', ['biceps', 'rear_delts'],      'cable',        'pull',      true,  10, 15, 3, 4],
  ['Machine Row (Hammer Strength)', 'back', ['biceps'],                    'machine',      'pull',      true,  10, 15, 3, 4],
  ['TRX Row',                       'back', ['biceps'],                    'bodyweight',   'pull',      true,  10, 20, 2, 4],
  ['Banded Row',                    'back', ['biceps'],                    'bodyweight',   'pull',      true,  12, 20, 1, 4],
  ['Back Extension (Weighted)',     'back', ['glutes', 'hamstrings'],      'machine',      'hinge',     true,  12, 20, 2, 4],

  // ─── SHOULDERS (split by delt head) ─────────────────────────────────────────
  // Front delts
  ['Barbell Overhead Press',        'front_delts', ['triceps', 'side_delts'], 'barbell',   'push',      true,  5, 10,  4, 3],
  ['Dumbbell Shoulder Press',       'front_delts', ['triceps', 'side_delts'], 'dumbbell',  'push',      true,  8, 15,  3, 4],
  ['Arnold Press',                  'front_delts', ['triceps', 'side_delts'], 'dumbbell',  'push',      true,  8, 12,  3, 4],
  ['Seated Dumbbell Press',         'front_delts', ['triceps', 'side_delts'], 'dumbbell',  'push',      true,  8, 15,  3, 4],
  ['Z-Press',                       'front_delts', ['triceps', 'side_delts'], 'barbell',   'push',      true,  5, 10,  3, 3],
  ['Push Press',                    'front_delts', ['triceps', 'side_delts'], 'barbell',   'push',      true,  3, 8,   4, 3],
  ['Dumbbell Front Raise',          'front_delts', [],                    'dumbbell',     'isolation', false, 12, 20, 2, 3],
  ['Cable Front Raise',             'front_delts', [],                    'cable',        'isolation', false, 12, 20, 2, 3],

  // Side delts
  ['Dumbbell Lateral Raise',        'side_delts', [],                     'dumbbell',     'isolation', false, 15, 25, 2, 5],
  ['Cable Lateral Raise',           'side_delts', [],                     'cable',        'isolation', false, 15, 25, 2, 5],
  ['Machine Lateral Raise',         'side_delts', [],                     'machine',      'isolation', false, 15, 25, 2, 5],
  ['Leaning Lateral Raise',         'side_delts', [],                     'dumbbell',     'isolation', false, 15, 25, 2, 5],
  ['Landmine Lateral Raise',        'side_delts', [],                     'barbell',      'isolation', false, 12, 20, 2, 4],
  ['Band Lateral Raise',            'side_delts', [],                     'bodyweight',   'isolation', false, 15, 25, 1, 4],
  ['Seated Lateral Raise',          'side_delts', [],                     'dumbbell',     'isolation', false, 15, 25, 2, 5],
  ['Upright Row',                   'side_delts', ['biceps', 'traps'],    'barbell',      'pull',      false, 10, 15, 3, 3],
  ['Machine Shoulder Press',        'side_delts', ['triceps', 'front_delts'], 'machine',  'push',      true,  8, 15,  3, 4],
  ['Viking Press',                  'side_delts', ['triceps', 'front_delts'], 'machine',  'push',      true,  8, 15,  3, 4],

  // Rear delts
  ['Dumbbell Rear Delt Fly',        'rear_delts', ['back'],               'dumbbell',     'isolation', false, 15, 25, 2, 5],
  ['Cable Rear Delt Fly',           'rear_delts', ['back'],               'cable',        'isolation', false, 15, 25, 2, 5],
  ['Machine Rear Delt Fly',         'rear_delts', ['back'],               'machine',      'isolation', false, 15, 25, 2, 5],
  ['Reverse Pec Deck',              'rear_delts', ['back'],               'machine',      'isolation', false, 15, 25, 2, 5],
  ['Cable Y-Raise (Prone)',         'rear_delts', ['back'],               'cable',        'pull',      false, 12, 20, 2, 5],
  ['Face Pull',                     'rear_delts', ['back', 'traps'],      'cable',        'pull',      false, 15, 25, 2, 5],
  ['Dumbbell Side-Lying Rear Delt', 'rear_delts', [],                     'dumbbell',     'isolation', false, 15, 25, 1, 5],
  ['W-Raise',                       'rear_delts', ['back', 'traps'],      'dumbbell',     'isolation', false, 12, 20, 1, 5],
  ['YTW',                           'rear_delts', ['back', 'traps'],      'dumbbell',     'isolation', false, 12, 20, 1, 5],
  ['Lying Rear Delt Row',           'rear_delts', ['back'],               'dumbbell',     'pull',      false, 15, 25, 2, 5],
  ['Cable Face Pull',               'rear_delts', ['back', 'traps'],      'cable',        'pull',      false, 15, 25, 2, 5],
  ['Band Face Pull',                'rear_delts', ['back', 'traps'],      'bodyweight',   'pull',      false, 15, 25, 1, 4],

  // ─── BICEPS ──────────────────────────────────────────────────────────────────
  ['Barbell Curl',                  'biceps', [],                         'barbell',      'isolation', false, 8, 12,  2, 4],
  ['EZ Bar Curl',                   'biceps', [],                         'ez_bar',       'isolation', false, 8, 12,  2, 4],
  ['Dumbbell Curl',                 'biceps', [],                         'dumbbell',     'isolation', false, 10, 15, 2, 4],
  ['Hammer Curl',                   'biceps', ['forearms'],               'dumbbell',     'isolation', false, 10, 15, 2, 4],
  ['Incline Dumbbell Curl',         'biceps', [],                         'dumbbell',     'isolation', false, 10, 15, 2, 5],
  ['Preacher Curl (Barbell)',       'biceps', [],                         'barbell',      'isolation', false, 8, 12,  2, 4],
  ['Preacher Curl (Dumbbell)',      'biceps', [],                         'dumbbell',     'isolation', false, 8, 12,  2, 4],
  ['Preacher Curl (EZ Bar)',        'biceps', [],                         'ez_bar',       'isolation', false, 8, 12,  2, 4],
  ['Cable Curl',                    'biceps', [],                         'cable',        'isolation', false, 10, 15, 2, 4],
  ['Cable Hammer Curl (Rope)',      'biceps', ['forearms'],               'cable',        'isolation', false, 10, 15, 2, 4],
  ['Machine Curl',                  'biceps', [],                         'machine',      'isolation', false, 10, 15, 2, 4],
  ['Concentration Curl',            'biceps', [],                         'dumbbell',     'isolation', false, 12, 15, 2, 5],
  ['Zottman Curl',                  'biceps', ['forearms'],               'dumbbell',     'isolation', false, 8, 12,  2, 4],
  ['Spider Curl',                   'biceps', [],                         'barbell',      'isolation', false, 8, 12,  2, 5],
  ['Cross-Body Hammer Curl',        'biceps', ['forearms'],               'dumbbell',     'isolation', false, 10, 15, 2, 4],
  ['Prone Incline Curl',            'biceps', [],                         'dumbbell',     'isolation', false, 10, 15, 2, 5],
  ['Reverse Curl',                  'biceps', ['forearms'],               'barbell',      'isolation', false, 10, 15, 2, 3],
  ['Cable Reverse Curl',            'biceps', ['forearms'],               'cable',        'isolation', false, 12, 20, 2, 3],

  // ─── TRICEPS ─────────────────────────────────────────────────────────────────
  ['Close-Grip Bench Press',        'triceps', ['chest', 'front_delts'],  'barbell',      'push',      true,  6, 12,  3, 3],
  ['EZ Bar Skull Crusher',          'triceps', [],                         'ez_bar',       'isolation', false, 8, 15,  2, 4],
  ['Dumbbell Skull Crusher',        'triceps', [],                         'dumbbell',     'isolation', false, 8, 15,  2, 4],
  ['Decline Skull Crusher',         'triceps', [],                         'barbell',      'isolation', false, 8, 15,  2, 4],
  ['Tricep Pushdown (Rope)',        'triceps', [],                         'cable',        'isolation', false, 12, 20, 2, 4],
  ['Tricep Pushdown (Bar)',         'triceps', [],                         'cable',        'isolation', false, 10, 20, 2, 4],
  ['Cable Pushdown (Straight Bar)', 'triceps', [],                         'cable',        'isolation', false, 10, 20, 2, 4],
  ['Rope Pushdown',                 'triceps', [],                         'cable',        'isolation', false, 12, 20, 2, 4],
  ['Overhead Cable Tricep Extension','triceps',[],                         'cable',        'isolation', false, 12, 20, 2, 5],
  ['Dumbbell Overhead Tricep Extension','triceps',[],                      'dumbbell',     'isolation', false, 10, 15, 2, 4],
  ['Overhead Dumbbell Extension',   'triceps', [],                         'dumbbell',     'isolation', false, 10, 15, 2, 4],
  ['Weighted Dips (Triceps)',       'triceps', ['chest', 'front_delts'],  'bodyweight',   'push',      true,  8, 15,  4, 3],
  ['Bench Dip',                     'triceps', ['chest', 'front_delts'],  'bodyweight',   'push',      true,  10, 20, 2, 3],
  ['Tricep Kickback',               'triceps', [],                         'dumbbell',     'isolation', false, 12, 20, 2, 3],
  ['Diamond Push-Up',               'triceps', ['chest'],                 'bodyweight',   'push',      true,  10, 20, 2, 3],
  ['JM Press',                      'triceps', ['chest'],                 'barbell',      'push',      true,  8, 12,  3, 4],
  ['Tate Press',                    'triceps', [],                         'dumbbell',     'isolation', false, 10, 15, 2, 4],
  ['Lying Tricep Extension',        'triceps', [],                         'dumbbell',     'isolation', false, 10, 15, 2, 4],
  ['Machine Tricep Extension',      'triceps', [],                         'machine',      'isolation', false, 12, 20, 2, 4],
  ['Single Arm Cable Extension',    'triceps', [],                         'cable',        'isolation', false, 12, 20, 2, 4],
  ['Board Press',                   'triceps', ['chest'],                 'barbell',      'push',      true,  5, 8,   3, 3],

  // ─── QUADS ───────────────────────────────────────────────────────────────────
  ['Barbell Back Squat',            'quads', ['glutes', 'hamstrings'],    'barbell',      'squat',     true,  5, 10,  5, 3],
  ['Barbell Front Squat',           'quads', ['glutes'],                  'barbell',      'squat',     true,  5, 10,  4, 3],
  ['Hack Squat Machine',            'quads', ['glutes'],                  'machine',      'squat',     true,  8, 15,  4, 4],
  ['Leg Press',                     'quads', ['glutes', 'hamstrings'],    'machine',      'squat',     true,  8, 20,  4, 4],
  ['Bulgarian Split Squat',         'quads', ['glutes'],                  'dumbbell',     'squat',     true,  8, 15,  4, 4],
  ['Leg Extension',                 'quads', [],                          'machine',      'isolation', false, 12, 25, 2, 5],
  ['Sissy Squat',                   'quads', [],                          'bodyweight',   'isolation', false, 10, 20, 3, 4],
  ['Goblet Squat',                  'quads', ['glutes'],                  'dumbbell',     'squat',     true,  10, 20, 3, 4],
  ['Dumbbell Lunge',                'quads', ['glutes'],                  'dumbbell',     'squat',     true,  10, 20, 3, 4],
  ['Walking Lunge',                 'quads', ['glutes', 'hamstrings'],    'dumbbell',     'squat',     true,  10, 20, 3, 4],
  ['Barbell Lunge',                 'quads', ['glutes'],                  'barbell',      'squat',     true,  8, 15,  4, 3],
  ['Step-Up (Dumbbell)',            'quads', ['glutes'],                  'dumbbell',     'squat',     true,  10, 15, 3, 4],
  ['Step-Up (Barbell)',             'quads', ['glutes'],                  'barbell',      'squat',     true,  8, 12,  4, 3],
  ['Wall Sit',                      'quads', [],                          'bodyweight',   'isolation', false, 30, 90, 2, 3],
  ['Cyclist Squat',                 'quads', [],                          'barbell',      'squat',     true,  8, 15,  4, 4],
  ['Smith Machine Squat',           'quads', ['glutes'],                  'smith_machine','squat',     true,  8, 15,  4, 4],
  ['Box Squat',                     'quads', ['glutes', 'hamstrings'],    'barbell',      'squat',     true,  5, 10,  4, 3],
  ['Pause Squat',                   'quads', ['glutes'],                  'barbell',      'squat',     true,  5, 8,   4, 3],
  ['Heel-Elevated Squat',           'quads', [],                          'barbell',      'squat',     true,  8, 15,  4, 4],
  ['Single Leg Press',              'quads', ['glutes'],                  'machine',      'squat',     true,  10, 20, 3, 4],
  ['Pendulum Squat',                'quads', ['glutes'],                  'machine',      'squat',     true,  8, 15,  4, 4],
  ['Spanish Squat',                 'quads', [],                          'bodyweight',   'isolation', false, 10, 20, 3, 4],
  ['Leg Press (Narrow Stance)',     'quads', [],                          'machine',      'squat',     true,  8, 20,  4, 4],
  ['Sumo Squat',                    'quads', ['glutes', 'hamstrings'],    'barbell',      'squat',     true,  8, 15,  4, 3],

  // ─── HAMSTRINGS ──────────────────────────────────────────────────────────────
  ['Romanian Deadlift',             'hamstrings', ['glutes', 'back'],     'barbell',      'hinge',     true,  6, 12,  4, 4],
  ['Romanian Deadlift (Barbell)',   'hamstrings', ['glutes', 'back'],     'barbell',      'hinge',     true,  6, 12,  4, 4],
  ['Romanian Deadlift (Dumbbell)',  'hamstrings', ['glutes'],             'dumbbell',     'hinge',     true,  8, 15,  3, 4],
  ['Stiff-Leg Deadlift',           'hamstrings', ['back', 'glutes'],     'barbell',      'hinge',     true,  6, 12,  4, 4],
  ['Nordic Curl',                   'hamstrings', [],                     'bodyweight',   'isolation', false, 3, 10,  3, 5],
  ['Nordic Hamstring Curl',         'hamstrings', [],                     'bodyweight',   'isolation', false, 3, 10,  3, 5],
  ['Lying Leg Curl',                'hamstrings', [],                     'machine',      'isolation', false, 10, 15, 2, 5],
  ['Seated Leg Curl',               'hamstrings', [],                     'machine',      'isolation', false, 10, 15, 2, 5],
  ['Standing Leg Curl',             'hamstrings', [],                     'machine',      'isolation', false, 10, 15, 2, 5],
  ['Leg Curl (Cable)',              'hamstrings', [],                     'cable',        'isolation', false, 10, 15, 2, 4],
  ['Good Morning',                  'hamstrings', ['back', 'glutes'],     'barbell',      'hinge',     true,  8, 15,  4, 3],
  ['Glute Ham Raise',               'hamstrings', ['glutes'],             'machine',      'isolation', false, 5, 12,  3, 5],
  ['Single-Leg Romanian Deadlift',  'hamstrings', ['glutes'],             'dumbbell',     'hinge',     true,  8, 12,  3, 4],
  ['Single-Leg Romanian Deadlift (DB)', 'hamstrings', ['glutes'],        'dumbbell',     'hinge',     true,  8, 12,  3, 4],
  ['B-Stance Romanian Deadlift',    'hamstrings', ['glutes'],             'barbell',      'hinge',     true,  8, 12,  3, 4],
  ['Swiss Ball Leg Curl',           'hamstrings', ['glutes'],             'bodyweight',   'isolation', false, 10, 20, 2, 5],
  ['Cable Pull-Through',            'hamstrings', ['glutes'],             'cable',        'hinge',     true,  12, 20, 2, 5],
  ['Kettlebell Swing',              'hamstrings', ['glutes', 'back'],     'kettlebell',   'hinge',     true,  10, 20, 3, 4],
  ['Deadlift (Conventional)',       'hamstrings', ['back', 'glutes', 'quads'], 'barbell', 'hinge',    true,  3, 8,   5, 3],
  ['Deadlift (Sumo)',               'hamstrings', ['back', 'glutes', 'quads'], 'barbell', 'hinge',    true,  3, 8,   5, 3],
  ['Trap Bar Deadlift (Hamstring)', 'hamstrings', ['back', 'glutes'],     'barbell',      'hinge',     true,  4, 8,   5, 4],

  // ─── GLUTES ──────────────────────────────────────────────────────────────────
  ['Barbell Hip Thrust',            'glutes', ['hamstrings', 'quads'],    'barbell',      'hinge',     true,  8, 15,  3, 5],
  ['Dumbbell Hip Thrust',           'glutes', ['hamstrings'],             'dumbbell',     'hinge',     true,  10, 20, 3, 5],
  ['Smith Machine Hip Thrust',      'glutes', ['hamstrings'],             'smith_machine','hinge',     true,  10, 20, 3, 5],
  ['Machine Hip Thrust',            'glutes', ['hamstrings'],             'machine',      'hinge',     true,  10, 20, 2, 5],
  ['Glute Bridge',                  'glutes', ['hamstrings'],             'bodyweight',   'hinge',     true,  12, 20, 2, 4],
  ['Single Leg Hip Thrust',         'glutes', ['hamstrings'],             'bodyweight',   'hinge',     true,  10, 20, 2, 5],
  ['Frog Pump',                     'glutes', [],                         'bodyweight',   'isolation', false, 15, 30, 1, 4],
  ['Cable Kickback',                'glutes', [],                         'cable',        'isolation', false, 15, 25, 2, 5],
  ['Donkey Kick',                   'glutes', [],                         'bodyweight',   'isolation', false, 15, 25, 1, 4],
  ['Abduction Machine',             'glutes', [],                         'machine',      'isolation', false, 15, 25, 2, 4],
  ['Cable Hip Abduction',           'glutes', [],                         'cable',        'isolation', false, 15, 25, 2, 4],
  ['Banded Walk',                   'glutes', [],                         'bodyweight',   'isolation', false, 15, 30, 1, 4],
  ['Step-Up (Glute Focus)',         'glutes', ['quads'],                  'dumbbell',     'squat',     true,  10, 15, 3, 4],
  ['Sumo Squat (Glute Focus)',      'glutes', ['hamstrings'],             'dumbbell',     'squat',     true,  10, 20, 3, 4],
  ['Nordic Glute Curl',             'glutes', ['hamstrings'],             'bodyweight',   'isolation', false, 5, 12,  3, 5],
  ['45-Degree Hip Extension',       'glutes', ['hamstrings', 'back'],     'machine',      'hinge',     true,  12, 20, 2, 4],
  ['Reverse Hyperextension (Glute)','glutes', ['hamstrings'],             'machine',      'hinge',     true,  12, 20, 2, 5],
  ['Sumo Deadlift (Glute Focus)',   'glutes', ['hamstrings', 'quads'],    'barbell',      'hinge',     true,  5, 10,  5, 3],

  // ─── CALVES ──────────────────────────────────────────────────────────────────
  ['Standing Calf Raise (Machine)', 'calves', [],                         'machine',      'isolation', false, 10, 20, 2, 4],
  ['Standing Calf Raise (Barbell)', 'calves', [],                         'barbell',      'isolation', false, 10, 20, 2, 4],
  ['Seated Calf Raise',             'calves', [],                         'machine',      'isolation', false, 15, 25, 2, 4],
  ['Seated Machine Calf Raise',     'calves', [],                         'machine',      'isolation', false, 15, 25, 2, 4],
  ['Seated Dumbbell Calf Raise',    'calves', [],                         'dumbbell',     'isolation', false, 15, 25, 2, 4],
  ['Leg Press Calf Raise',          'calves', [],                         'machine',      'isolation', false, 15, 25, 2, 4],
  ['Donkey Calf Raise',             'calves', [],                         'bodyweight',   'isolation', false, 15, 25, 2, 4],
  ['Single-Leg Calf Raise (Bodyweight)','calves',[],                      'bodyweight',   'isolation', false, 15, 25, 2, 4],
  ['Dumbbell Calf Raise (Standing)','calves', [],                         'dumbbell',     'isolation', false, 12, 20, 2, 4],
  ['Smith Machine Calf Raise',      'calves', [],                         'smith_machine','isolation', false, 10, 20, 2, 4],
  ['Calf Raise on Steps',           'calves', [],                         'bodyweight',   'isolation', false, 15, 25, 1, 4],
  ['Box Jump',                      'calves', ['quads', 'glutes'],        'bodyweight',   'plyometric',true,  5, 10,  3, 4],

  // ─── ABS / CORE ──────────────────────────────────────────────────────────────
  ['Cable Crunch',                  'abs', [],                            'cable',        'isolation', false, 15, 25, 2, 5],
  ['Hanging Leg Raise',             'abs', [],                            'bodyweight',   'isolation', false, 10, 20, 2, 5],
  ['Plank',                         'abs', [],                            'bodyweight',   'isolation', false, 20, 60, 2, 4],
  ['Side Plank',                    'abs', [],                            'bodyweight',   'isolation', false, 20, 60, 1, 4],
  ['Ab Rollout',                    'abs', [],                            'bodyweight',   'isolation', false, 8, 15,  2, 5],
  ['Ab Wheel Rollout',              'abs', [],                            'bodyweight',   'isolation', false, 8, 15,  2, 5],
  ['Decline Crunch',                'abs', [],                            'bodyweight',   'isolation', false, 15, 25, 2, 4],
  ['Russian Twist',                 'abs', [],                            'bodyweight',   'isolation', false, 20, 30, 2, 4],
  ['Pallof Press',                  'abs', [],                            'cable',        'isolation', false, 10, 15, 2, 5],
  ['Landmine Twist',                'abs', [],                            'barbell',      'isolation', false, 10, 15, 2, 4],
  ['Landmine Rotation',             'abs', [],                            'barbell',      'isolation', false, 10, 15, 2, 4],
  ['Bicycle Crunch',                'abs', [],                            'bodyweight',   'isolation', false, 20, 30, 1, 4],
  ['Crunch',                        'abs', [],                            'bodyweight',   'isolation', false, 15, 30, 1, 3],
  ['Reverse Crunch',                'abs', [],                            'bodyweight',   'isolation', false, 15, 25, 1, 4],
  ['Leg Raise',                     'abs', [],                            'bodyweight',   'isolation', false, 15, 25, 1, 4],
  ['Leg Raise (Flat Bench)',        'abs', [],                            'bodyweight',   'isolation', false, 15, 25, 1, 4],
  ['Dragon Flag',                   'abs', [],                            'bodyweight',   'isolation', false, 5, 10,  3, 5],
  ['V-Up',                          'abs', [],                            'bodyweight',   'isolation', false, 10, 20, 2, 4],
  ['Sit-Up',                        'abs', [],                            'bodyweight',   'isolation', false, 15, 30, 1, 3],
  ['Cable Woodchop',                'abs', [],                            'cable',        'isolation', false, 10, 15, 2, 4],
  ['Machine Crunch',                'abs', [],                            'machine',      'isolation', false, 15, 25, 2, 4],
  ['Dead Bug',                      'abs', [],                            'bodyweight',   'isolation', false, 8, 15,  2, 5],
  ['Hollow Body Hold',              'abs', [],                            'bodyweight',   'isolation', false, 10, 30, 2, 4],
  ['Stir the Pot',                  'abs', [],                            'bodyweight',   'isolation', false, 8, 15,  2, 5],

  // ─── TRAPS ───────────────────────────────────────────────────────────────────
  ['Barbell Shrug',                 'traps', [],                          'barbell',      'isolation', false, 12, 20, 2, 4],
  ['Dumbbell Shrug',                'traps', [],                          'dumbbell',     'isolation', false, 12, 20, 2, 4],
  ['Cable Shrug',                   'traps', [],                          'cable',        'isolation', false, 12, 20, 2, 4],
  ['Smith Machine Shrug',           'traps', [],                          'smith_machine','isolation', false, 12, 20, 2, 4],
  ['Hex Bar Shrug',                 'traps', [],                          'barbell',      'isolation', false, 12, 20, 3, 4],
  ['Behind-the-Back Barbell Shrug', 'traps', [],                          'barbell',      'isolation', false, 12, 20, 2, 4],
  ["Farmer's Walk",                 'traps', ['forearms', 'abs'],         'dumbbell',     'carry',     true,  20, 40, 3, 4],
  ['Power Clean',                   'traps', ['quads', 'glutes', 'back'], 'barbell',      'power',     true,  3, 5,   5, 3],
  ['Rack Pull (Traps)',             'traps', ['back'],                    'barbell',      'hinge',     true,  5, 10,  4, 3],
  ['Face Pull (Traps)',             'traps', ['rear_delts'],              'cable',        'pull',      false, 15, 25, 2, 4],

  // ─── FOREARMS ────────────────────────────────────────────────────────────────
  ['Barbell Wrist Curl',            'forearms', [],                       'barbell',      'isolation', false, 15, 25, 2, 3],
  ['Reverse Wrist Curl',            'forearms', [],                       'barbell',      'isolation', false, 15, 25, 2, 3],
  ['Dumbbell Wrist Curl',           'forearms', [],                       'dumbbell',     'isolation', false, 15, 25, 1, 3],
  ['Plate Pinch',                   'forearms', [],                       'barbell',      'isolation', false, 30, 60, 2, 3],
  ['Dead Hang',                     'forearms', ['back'],                 'bodyweight',   'isolation', false, 20, 60, 2, 4],
  ['Thick Bar Curl',                'forearms', ['biceps'],               'barbell',      'isolation', false, 8, 12,  2, 3],
  ['Cable Reverse Curl (Forearms)', 'forearms', ['biceps'],               'cable',        'isolation', false, 12, 20, 2, 3],
  ['Farmer Walk (Forearms)',        'forearms', ['traps'],                'dumbbell',     'carry',     true,  20, 40, 3, 4],

  // ─── NECK ────────────────────────────────────────────────────────────────────
  ['Neck Flexion (Machine)',        'neck', [],                           'machine',      'isolation', false, 15, 25, 1, 4],
  ['Neck Extension (Machine)',      'neck', [],                           'machine',      'isolation', false, 15, 25, 1, 4],
  ['Neck Lateral Flexion',          'neck', [],                           'bodyweight',   'isolation', false, 15, 25, 1, 3],
  ['Neck Curl',                     'neck', [],                           'bodyweight',   'isolation', false, 15, 25, 1, 3],
  ['Neck Bridge',                   'neck', ['traps'],                   'bodyweight',   'isolation', false, 15, 30, 2, 3],
];

export async function seedExercisesIfNeeded() {
  try {
    const seeded = await AsyncStorage.getItem(SEEDED_KEY);
    if (seeded === 'true') return;

    const existing = await getAllExercises();
    if (existing.length > 0) {
      await AsyncStorage.setItem(SEEDED_KEY, 'true');
      return;
    }

    for (const row of RAW) {
      const [name, primaryMuscle, secondaryMuscles, equipment, movementPattern, isCompound, min, max, fatigue, sfr] = row;
      await insertExercise({
        name,
        primaryMuscle,
        secondaryMuscles,
        equipment,
        movementPattern,
        compoundIsolation: isCompound ? 'compound' : 'isolation',
        defaultRepMin: min,
        defaultRepMax: max,
        fatigueCost: fatigue,
        stimulusToFatigueRatio: sfr,
        subregion: SUBREGION_MAP[name] ?? null,
        isCustom: false,
      });
    }

    await AsyncStorage.setItem(SEEDED_KEY, 'true');
    console.log(`[Seed] Inserted ${RAW.length} exercises`);
  } catch (err) {
    console.error('[Seed] seedExercisesIfNeeded failed:', err);
  }
}
