-- Migration 150: RETIRED, NEVER TO BE RUN (founder no-outside-party law
-- + Q4 internal ruling, 2026-08-21).
--
-- As written, this migration added five capability operational counters
-- to record_engine_telemetry's allow-list. Those events would land in
-- engine_telemetry keyed per user, and the PRESENCE of such an event
-- alone can reveal that a user has capability (health-adjacent) rules.
-- The internal ruling under published ICO special-category guidance is
-- deliberately conservative: no capability-derived event leaves the
-- device at all. The client emission sites and the events.js catalogue
-- entries were removed the same day, so there is nothing for this
-- allow-list to accept.
--
-- Status: RETIRED UNAPPLIED. It was never run against production.
-- Do NOT include this file in any production batch; the capability run
-- set is 145-149 and 151. The file is kept so the migration numbering
-- stays continuous and the history honest.
--
-- If capability operational telemetry is ever wanted again, it must be
-- designed aggregate-only and identity-free from the start (no user_id
-- on capability events; minimum-cohort suppression per published
-- anonymisation guidance) and arrive as a NEW migration.
--
-- Safe to re-run trivially: this file intentionally contains no
-- statements. Rollback: nothing to roll back.

-- (no statements)
