/**
 * kettlebell.js — generated by scripts/exercise-library/convert-legacy.mjs
 * (EL-14, docs/exercise-library-expansion-2026-09-05/07-CORPUS-FORMAT.md
 * section 1-2). 6 entries, converted one-to-one from the legacy
 * seedExercises.js RAW tuple (plus seedRoutines.js REQUIRED_EXERCISES,
 * EL-15) with names UNCHANGED (canonical id is a hash of the name).
 *
 * Conventions: alphabetical within each movement section; pure object
 * literals, no imports except from ./vocab.js; cue is '' until a later
 * agent authors it (EL-17); a retired entry ({ name, retiredInto }) marks
 * an EL-21 duplicate-consolidation, kept so its canonical id stays
 * resolvable for the id-remap top-up.
 *
 * Sources policy: every row here already shipped in production; this is
 * a format migration, not new content. New rows added in a later stage of
 * this campaign follow EL-3's quality gate and are attested against
 * coaching/exercise-science literature or the open datasets checklist.
 */

export default [
  {
    name: "Kettlebell Clean and Press",
    primaryMuscle: "front_delts",
    secondaryMuscles: ["glutes","traps"],
    equipment: "kettlebell",
    movementPattern: "push",
    compound: true,
    repMin: 5, repMax: 10,
    fatigueCost: 4, sfr: 4,
    subregion: "overhead_press",
    aliases: ["KB Clean and Press"],
    loadCharacter: "ballistic",
    cue: "",
  },
  {
    name: "Kettlebell Romanian Deadlift",
    primaryMuscle: "hamstrings",
    secondaryMuscles: ["glutes"],
    equipment: "kettlebell",
    movementPattern: "hinge",
    compound: true,
    repMin: 10, repMax: 15,
    fatigueCost: 3, sfr: 4,
    subregion: "hip_extension",
    aliases: ["KB Romanian Deadlift"],
    loadCharacter: "grind",
    cue: "",
  },
  {
    name: "Kettlebell Shrug",
    primaryMuscle: "traps",
    secondaryMuscles: [],
    equipment: "kettlebell",
    movementPattern: "isolation",
    compound: false,
    repMin: 12, repMax: 20,
    fatigueCost: 2, sfr: 4,
    subregion: null,
    aliases: ["KB Shrug"],
    loadCharacter: "grind",
    cue: "",
  },
  {
    name: "Kettlebell Snatch",
    primaryMuscle: "back",
    secondaryMuscles: ["glutes","hamstrings"],
    equipment: "kettlebell",
    movementPattern: "hinge",
    compound: true,
    repMin: 5, repMax: 10,
    fatigueCost: 4, sfr: 4,
    subregion: "upper_mid_row",
    aliases: ["KB Snatch"],
    loadCharacter: "ballistic",
    cue: "",
  },
  {
    name: "Kettlebell Swing",
    primaryMuscle: "hamstrings",
    secondaryMuscles: ["glutes","back"],
    equipment: "kettlebell",
    movementPattern: "hinge",
    compound: true,
    repMin: 10, repMax: 20,
    fatigueCost: 3, sfr: 4,
    subregion: "hip_extension",
    aliases: ["KB Swing"],
    loadCharacter: "ballistic",
    cue: "",
  },
  {
    name: "Turkish Get-Up",
    primaryMuscle: "abs",
    secondaryMuscles: ["glutes","front_delts"],
    equipment: "kettlebell",
    movementPattern: "isolation",
    compound: false,
    repMin: 3, repMax: 6,
    fatigueCost: 3, sfr: 5,
    subregion: "anti_extension",
    aliases: ["TGU"],
    loadCharacter: "grind",
    cue: "",
  },
];
