/**
 * medicine_ball.js — generated by scripts/exercise-library/convert-legacy.mjs
 * (EL-14, docs/exercise-library-expansion-2026-09-05/07-CORPUS-FORMAT.md
 * section 1-2). 0 entries, converted one-to-one from the legacy
 * seedExercises.js RAW tuple (plus seedRoutines.js REQUIRED_EXERCISES,
 * EL-15) with names UNCHANGED (canonical id is a hash of the name).
 *
 * Conventions: alphabetical within each movement section; pure object
 * literals, no imports except from ./vocab.js; cue is '' until a later
 * agent authors it (EL-17); a retired entry ({ name, retiredInto }) marks
 * an EL-21 duplicate-consolidation, kept so its canonical id stays
 * resolvable for the id-remap top-up.
 *
 * Sources policy: every row here already shipped in production; this is
 * a format migration, not new content. New rows added in a later stage of
 * this campaign follow EL-3's quality gate and are attested against
 * coaching/exercise-science literature or the open datasets checklist.
 */

export default [

  // ── INTEGRATION STAGE 2 (exercise-library-expansion-2026-09-05) — generated by scripts/exercise-library/integrate-inventories.mjs; rerun the script to regenerate, do not hand-edit below this line ──
  {
    name: "Medicine Ball Chest Pass",
    primaryMuscle: "chest",
    secondaryMuscles: ["triceps","front_delts"],
    equipment: "medicine_ball",
    movementPattern: "power",
    compound: true,
    repMin: 5, repMax: 10,
    fatigueCost: 3, sfr: 4,
    subregion: "flat",
    aliases: ["Medicine Ball Push Pass","medicine ball chest push multiple response","medicine ball chest push single response","Chest Push (multiple response)","Chest Push (single response)"],
    loadCharacter: "ballistic",
    overrides: {"demands":{"position":"standing","floorAccess":false,"overheadPosition":false,"gripDemand":"supportive","unilateralLoadable":false,"bilateralUpper":true,"bilateralLower":false,"axialLoad":false,"impact":false,"balanceDemand":"stable","weightBearingHands":false}},
    setup: "Hold the ball at your chest, elbows bent, facing a wall or partner.",
    execution: "Extend your arms explosively to throw it straight out, then catch it as it returns and absorb it back to your chest.",
    watch: "Pushing with your arms alone leaves the legs out, so drive from your feet as you throw.",
  },
  {
    name: "Medicine Ball Overhead Throw",
    primaryMuscle: "chest",
    secondaryMuscles: ["front_delts","triceps"],
    equipment: "medicine_ball",
    movementPattern: "power",
    compound: true,
    repMin: 5, repMax: 10,
    fatigueCost: 3, sfr: 3,
    subregion: "incline",
    aliases: ["Overhead Soccer Throw","Medicine Ball Backward Overhead Throw","Catch and Overhead Throw","Standing Two-Arm Overhead Throw"],
    loadCharacter: "ballistic",
    overrides: {"demands":{"position":"standing","floorAccess":false,"overheadPosition":true,"gripDemand":"supportive","unilateralLoadable":false,"bilateralUpper":true,"bilateralLower":false,"axialLoad":true,"impact":false,"balanceDemand":"stable","weightBearingHands":false}},
    setup: "Hold the ball overhead with arms extended, feet slightly staggered.",
    execution: "Snap your torso forward and throw the ball down and forward into the floor or a wall with full effort.",
    watch: "Bending only at the arms keeps your torso out of it, so snap from the hips and ribs.",
  },
  {
    name: "Medicine Ball Rotational Throw",
    primaryMuscle: "abs",
    secondaryMuscles: ["glutes","chest"],
    equipment: "medicine_ball",
    movementPattern: "power",
    compound: true,
    repMin: 5, repMax: 10,
    fatigueCost: 3, sfr: 3,
    subregion: "rotation",
    aliases: ["Medicine Ball Side Throw","Rotational Med Ball Throw"],
    loadCharacter: "ballistic",
    overrides: {"laterality":"unilateral","demands":{"position":"standing","floorAccess":false,"overheadPosition":false,"gripDemand":"supportive","unilateralLoadable":false,"bilateralUpper":true,"bilateralLower":false,"axialLoad":false,"impact":false,"balanceDemand":"stable","weightBearingHands":false}},
    setup: "Stand side on to a wall holding the ball at your hip with both hands.",
    execution: "Rotate your hips and torso together and release the ball explosively towards the wall, then catch the rebound and reset.",
    watch: "Turning your shoulders while your hips stay still costs most of the throw, so let the back foot pivot.",
  },
  {
    name: "Medicine Ball Scoop Toss",
    primaryMuscle: "glutes",
    secondaryMuscles: ["abs","quads"],
    equipment: "medicine_ball",
    movementPattern: "power",
    compound: true,
    repMin: 5, repMax: 10,
    fatigueCost: 4, sfr: 3,
    subregion: "activator",
    aliases: ["Rotational Scoop Toss","Medicine Ball Scoop Throw"],
    loadCharacter: "ballistic",
    overrides: {"laterality":"unilateral","difficulty":3,"demands":{"position":"standing","floorAccess":false,"overheadPosition":false,"gripDemand":"supportive","unilateralLoadable":false,"bilateralUpper":true,"bilateralLower":true,"axialLoad":true,"impact":false,"balanceDemand":"stable","weightBearingHands":false}},
    setup: "Stand with the ball held low near one hip, knees bent.",
    execution: "Drive up through your legs and swing the ball diagonally across your body, releasing it up and out at the top.",
    watch: "Swinging with the arms while your legs stay straight loses the drive, so bend and extend the knees.",
  },
  {
    name: "Medicine Ball Slam",
    primaryMuscle: "abs",
    secondaryMuscles: ["back","triceps"],
    equipment: "medicine_ball",
    movementPattern: "power",
    compound: true,
    repMin: 6, repMax: 12,
    fatigueCost: 4, sfr: 3,
    subregion: "anti_extension",
    aliases: ["Overhead Medicine Ball Slam","Overhead Slam"],
    loadCharacter: "ballistic",
    overrides: {"difficulty":1,"demands":{"position":"standing","floorAccess":false,"overheadPosition":true,"gripDemand":"supportive","unilateralLoadable":false,"bilateralUpper":true,"bilateralLower":false,"axialLoad":true,"impact":false,"balanceDemand":"stable","weightBearingHands":false}},
    setup: "Hold the ball overhead with arms extended, feet shoulder-width apart.",
    execution: "Slam it down into the floor as hard as you can by driving through your torso, then catch the bounce or pick it back up.",
    watch: "Slamming from the elbows only keeps your torso out of it, so fold from the ribs as the ball drops.",
  },
  // ── END INTEGRATION STAGE 2 ──
];
