/**
 * sled.js — generated by scripts/exercise-library/convert-legacy.mjs
 * (EL-14, docs/exercise-library-expansion-2026-09-05/07-CORPUS-FORMAT.md
 * section 1-2). 0 entries, converted one-to-one from the legacy
 * seedExercises.js RAW tuple (plus seedRoutines.js REQUIRED_EXERCISES,
 * EL-15) with names UNCHANGED (canonical id is a hash of the name).
 *
 * Conventions: alphabetical within each movement section; pure object
 * literals, no imports except from ./vocab.js; cue is '' until a later
 * agent authors it (EL-17); a retired entry ({ name, retiredInto }) marks
 * an EL-21 duplicate-consolidation, kept so its canonical id stays
 * resolvable for the id-remap top-up.
 *
 * Sources policy: every row here already shipped in production; this is
 * a format migration, not new content. New rows added in a later stage of
 * this campaign follow EL-3's quality gate and are attested against
 * coaching/exercise-science literature or the open datasets checklist.
 */

export default [

  // ── INTEGRATION STAGE 2 (exercise-library-expansion-2026-09-05) — generated by scripts/exercise-library/integrate-inventories.mjs; rerun the script to regenerate, do not hand-edit below this line ──
  {
    name: "Sled Lateral Drag",
    primaryMuscle: "adductors",
    secondaryMuscles: ["glutes","quads"],
    equipment: "sled",
    movementPattern: "squat",
    compound: true,
    repMin: 15, repMax: 30,
    fatigueCost: 3, sfr: 4,
    subregion: null,
    aliases: ["Lateral Sled Drag"],
    loadCharacter: "grind",
    overrides: {"exerciseType":"duration","demands":{"position":"standing","floorAccess":false,"overheadPosition":false,"gripDemand":"supportive","unilateralLoadable":false,"bilateralUpper":false,"bilateralLower":true,"axialLoad":true,"impact":false,"balanceDemand":"stable","weightBearingHands":false}},
    cue: "Stand side on to the sled with the strap or rope attached, athletic stance with knees bent. Step sideways to drag the sled across the floor, keeping your hips low and chest up throughout. Standing too upright takes tension off the legs.",
  },
  {
    name: "Sled Reverse Drag",
    primaryMuscle: "quads",
    secondaryMuscles: ["calves"],
    equipment: "sled",
    movementPattern: "squat",
    compound: true,
    repMin: 15, repMax: 30,
    fatigueCost: 3, sfr: 5,
    subregion: "squat_press",
    aliases: ["Backward Sled Drag"],
    loadCharacter: "grind",
    overrides: {"exerciseType":"duration","difficulty":1,"demands":{"position":"standing","floorAccess":false,"overheadPosition":false,"gripDemand":"supportive","unilateralLoadable":false,"bilateralUpper":false,"bilateralLower":true,"axialLoad":true,"impact":false,"balanceDemand":"stable","weightBearingHands":false}},
    cue: "Face the sled and hold the strap with both hands, athletic stance with knees bent. Walk backward to drag the sled towards you, taking controlled steps and keeping tension on the strap. Letting the strap go slack loses the constant tension.",
  },
  {
    name: "Sled Row",
    primaryMuscle: "back",
    secondaryMuscles: ["biceps","rear_delts"],
    equipment: "sled",
    movementPattern: "pull",
    compound: true,
    repMin: 15, repMax: 30,
    fatigueCost: 3, sfr: 5,
    subregion: "horizontal_lat",
    aliases: ["Sled Rope Row"],
    loadCharacter: "grind",
    overrides: {"exerciseType":"duration","difficulty":1,"demands":{"position":"standing","floorAccess":false,"overheadPosition":false,"gripDemand":"bar","unilateralLoadable":false,"bilateralUpper":true,"bilateralLower":false,"axialLoad":true,"impact":false,"balanceDemand":"stable","weightBearingHands":false}},
    cue: "Face away from the sled attached by a strap or rope, in a split or athletic stance. Pull the handles towards your ribs, then extend your arms forward to let the sled slide back before pulling again. Walking the pull loses back tension.",
  },
  // ── END INTEGRATION STAGE 2 ──
];
