/**
 * smith.js — generated by scripts/exercise-library/convert-legacy.mjs
 * (EL-14, docs/exercise-library-expansion-2026-09-05/07-CORPUS-FORMAT.md
 * section 1-2). 10 entries, converted one-to-one from the legacy
 * seedExercises.js RAW tuple (plus seedRoutines.js REQUIRED_EXERCISES,
 * EL-15) with names UNCHANGED (canonical id is a hash of the name).
 *
 * Conventions: alphabetical within each movement section; pure object
 * literals, no imports except from ./vocab.js; cue is '' until a later
 * agent authors it (EL-17); a retired entry ({ name, retiredInto }) marks
 * an EL-21 duplicate-consolidation, kept so its canonical id stays
 * resolvable for the id-remap top-up.
 *
 * Sources policy: every row here already shipped in production; this is
 * a format migration, not new content. New rows added in a later stage of
 * this campaign follow EL-3's quality gate and are attested against
 * coaching/exercise-science literature or the open datasets checklist.
 */

export default [
  {
    name: "Incline Smith Machine Press",
    primaryMuscle: "chest",
    secondaryMuscles: ["triceps","front_delts"],
    equipment: "smith_machine",
    movementPattern: "push",
    compound: true,
    repMin: 8, repMax: 15,
    fatigueCost: 3, sfr: 4,
    subregion: "incline",
    loadCharacter: "grind",
    cue: "",
  },
  {
    name: "Smith Machine Bench Press",
    primaryMuscle: "chest",
    secondaryMuscles: ["triceps","front_delts"],
    equipment: "smith_machine",
    movementPattern: "push",
    compound: true,
    repMin: 6, repMax: 12,
    fatigueCost: 3, sfr: 3,
    subregion: "flat",
    loadCharacter: "grind",
    cue: "",
  },
  {
    name: "Smith Machine Calf Raise",
    primaryMuscle: "calves",
    secondaryMuscles: [],
    equipment: "smith_machine",
    movementPattern: "isolation",
    compound: false,
    repMin: 10, repMax: 20,
    fatigueCost: 2, sfr: 4,
    subregion: "gastro",
    loadCharacter: "grind",
    cue: "",
  },
  {
    name: "Smith Machine Close-Grip Press",
    primaryMuscle: "triceps",
    secondaryMuscles: ["chest"],
    equipment: "smith_machine",
    movementPattern: "push",
    compound: true,
    repMin: 8, repMax: 15,
    fatigueCost: 3, sfr: 3,
    subregion: "pushdown",
    loadCharacter: "grind",
    cue: "",
  },
  {
    name: "Smith Machine Front Squat",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes"],
    equipment: "smith_machine",
    movementPattern: "squat",
    compound: true,
    repMin: 6, repMax: 12,
    fatigueCost: 4, sfr: 4,
    subregion: "squat_press",
    loadCharacter: "grind",
    cue: "",
  },
  {
    name: "Smith Machine Hip Thrust",
    primaryMuscle: "glutes",
    secondaryMuscles: ["hamstrings"],
    equipment: "smith_machine",
    movementPattern: "hinge",
    compound: true,
    repMin: 10, repMax: 20,
    fatigueCost: 3, sfr: 5,
    subregion: "activator",
    loadCharacter: "grind",
    cue: "",
  },
  {
    name: "Smith Machine Incline Press",
    primaryMuscle: "chest",
    secondaryMuscles: ["triceps","front_delts"],
    equipment: "smith_machine",
    movementPattern: "push",
    compound: true,
    repMin: 8, repMax: 15,
    fatigueCost: 3, sfr: 4,
    subregion: "incline",
    loadCharacter: "grind",
    cue: "",
  },
  {
    name: "Smith Machine Row",
    primaryMuscle: "back",
    secondaryMuscles: ["biceps"],
    equipment: "smith_machine",
    movementPattern: "pull",
    compound: true,
    repMin: 8, repMax: 15,
    fatigueCost: 3, sfr: 4,
    subregion: "horizontal_lat",
    loadCharacter: "grind",
    cue: "",
  },
  {
    name: "Smith Machine Shrug",
    primaryMuscle: "traps",
    secondaryMuscles: [],
    equipment: "smith_machine",
    movementPattern: "isolation",
    compound: false,
    repMin: 12, repMax: 20,
    fatigueCost: 2, sfr: 4,
    subregion: null,
    loadCharacter: "grind",
    cue: "",
  },
  {
    name: "Smith Machine Squat",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes"],
    equipment: "smith_machine",
    movementPattern: "squat",
    compound: true,
    repMin: 8, repMax: 15,
    fatigueCost: 4, sfr: 4,
    subregion: "squat_press",
    loadCharacter: "grind",
    cue: "",
  },
];
