/**
 * suspension.js — generated by scripts/exercise-library/convert-legacy.mjs
 * (EL-14, docs/exercise-library-expansion-2026-09-05/07-CORPUS-FORMAT.md
 * section 1-2). 3 entries, converted one-to-one from the legacy
 * seedExercises.js RAW tuple (plus seedRoutines.js REQUIRED_EXERCISES,
 * EL-15) with names UNCHANGED (canonical id is a hash of the name).
 *
 * Conventions: alphabetical within each movement section; pure object
 * literals, no imports except from ./vocab.js; cue is '' until a later
 * agent authors it (EL-17); a retired entry ({ name, retiredInto }) marks
 * an EL-21 duplicate-consolidation, kept so its canonical id stays
 * resolvable for the id-remap top-up.
 *
 * Sources policy: every row here already shipped in production; this is
 * a format migration, not new content. New rows added in a later stage of
 * this campaign follow EL-3's quality gate and are attested against
 * coaching/exercise-science literature or the open datasets checklist.
 */

export default [
  {
    name: "Ring Push-Up",
    primaryMuscle: "chest",
    secondaryMuscles: ["triceps","front_delts"],
    equipment: "suspension",
    movementPattern: "push",
    compound: true,
    repMin: 8, repMax: 15,
    fatigueCost: 3, sfr: 4,
    subregion: "flat",
    loadCharacter: "grind",
    overrides: {"exerciseType":"weighted_bodyweight"},
    cue: "",
  },
  {
    name: "TRX Curl",
    primaryMuscle: "biceps",
    secondaryMuscles: [],
    equipment: "suspension",
    movementPattern: "isolation",
    compound: false,
    repMin: 10, repMax: 20,
    fatigueCost: 2, sfr: 4,
    subregion: "short_head",
    loadCharacter: "grind",
    cue: "",
  },
  {
    name: "TRX Row",
    primaryMuscle: "back",
    secondaryMuscles: ["biceps"],
    equipment: "suspension",
    movementPattern: "pull",
    compound: true,
    repMin: 10, repMax: 20,
    fatigueCost: 2, sfr: 4,
    subregion: "upper_mid_row",
    loadCharacter: "grind",
    cue: "",
  },
];
