/**
 * withEdgeToEdgeOptOut
 *
 * Android 15 (API 35) enforces edge-to-edge by default the moment
 * targetSdkVersion hits 35: the status and navigation bars go transparent and
 * the app is laid out behind them. Expo SDK 51 / React Navigation here do not
 * adapt to that, so screens that pad for the bottom safe-area inset end up with
 * an empty band between their content and the tab bar (the regression that
 * appeared right after the API 35 bump on the Train and Plans screens).
 *
 * Until the app is upgraded to handle edge-to-edge properly (Expo 52 ships
 * react-native-edge-to-edge for this), opt out so Android 15 keeps the pre-35
 * layout. `android:windowOptOutEdgeToEdgeEnforcement` exists on API 35 and is
 * ignored on older devices; Google support it until an app targets SDK 36.
 *
 * android/ is regenerated by `expo prebuild` in CI, so this has to be a config
 * plugin rather than a hand edit to styles.xml.
 */
const { withAndroidStyles } = require('@expo/config-plugins');

const ATTR = 'android:windowOptOutEdgeToEdgeEnforcement';

// Add (or refresh) the opt-out item on the app's main theme. Idempotent so
// re-running prebuild leaves a single entry. Pure, exported for the test.
function setOptOut(styles) {
  const styleArray = styles && styles.resources && styles.resources.style;
  if (!Array.isArray(styleArray)) return styles;
  const appTheme = styleArray.find((s) => s && s.$ && s.$.name === 'AppTheme');
  if (!appTheme) return styles;
  if (!Array.isArray(appTheme.item)) appTheme.item = [];
  appTheme.item = appTheme.item.filter((i) => !(i && i.$ && i.$.name === ATTR));
  appTheme.item.push({ _: 'true', $: { name: ATTR } });
  return styles;
}

const withEdgeToEdgeOptOut = (config) =>
  withAndroidStyles(config, (innerConfig) => {
    innerConfig.modResults = setOptOut(innerConfig.modResults);
    return innerConfig;
  });

module.exports = withEdgeToEdgeOptOut;
module.exports.setOptOut = setOptOut;
module.exports.ATTR = ATTR;
