#!/usr/bin/env node
// seed-sql.mjs — GD-24: generates supabase/seed_gyms_v1/ from
// data/gyms/brands.v1.json, data/gyms/postcode-sectors.v1.csv and
// data/gyms/uk-gyms.v1.jsonl.gz. Chunked files of at most 1,000 rows each
// (000-brands.sql, 001-sectors-NNN.sql, 1NN-venues-NNN.sql,
// 2NN-sources-NNN.sql), every chunk carrying the house header (purpose,
// applied status, safe-to-re-run, rollback) and
// INSERT ... ON CONFLICT (id) DO UPDATE (sectors conflict on `sector`).
// Columns exactly per docs/gym-database-2026-09-06/20-BLUEPRINT.md's
// "Data model" section — a source row's payload is never the raw source
// payload, only {source_status, source_dataset, licence} (task GD-24
// instruction). WRITTEN, NOT APPLIED: this script only writes .sql files;
// nothing here ever connects to Supabase or runs anything against it.
//
// GD-26 point 4: build.mjs's operator-feed coverage pass
// (verification_status = 'operator_unconfirmed', needs_review_reason =
// 'not_in_operator_feed') is carried through to `gym_venues` ONLY if that
// table already has matching columns for both — checked at generation
// time against supabase/migrate_162_gym_directory.sql's own text
// (lib/gymVenuesSchema.js), never by editing the migration.
// `verification_status` already exists there; `needs_review_reason` does
// not, so the fallback applies: the existing `needs_review` boolean column
// is set true for a flagged venue, and the reason is written instead to a
// new `4NN-history-NNN.sql` chunk as a `gym_venue_history` row
// (change = 'flag', after = {reason}, actor left NULL — this chunk is
// deliberately user-free, no id of any person).

import path from 'node:path';
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
const { readJsonlGz } = require('./lib/jsonl.js');
const { parseCsvHeader, csvLineToRecord } = require('./lib/csv.js');
const { gymVenuesHasAllColumns } = require('./lib/gymVenuesSchema.js');
const { uuidv5 } = require('./lib/uuid.js');

const DATA_DIR = path.join(__dirname, '../../data/gyms');
const BRANDS_FILE = path.join(DATA_DIR, 'brands.v1.json');
const SECTORS_FILE = path.join(DATA_DIR, 'postcode-sectors.v1.csv');
const VENUES_FILE = path.join(DATA_DIR, 'uk-gyms.v1.jsonl.gz');
const OUT_DIR = path.join(__dirname, '../../supabase/seed_gyms_v1');
// GD-26 point 4: read, never edited, to decide the needs_review_reason
// column fallback (see the module header note above).
const MIGRATION_FILE = path.join(__dirname, '../../supabase/migrate_162_gym_directory.sql');

const CHUNK_SIZE = 1000;
const BRAND_ID_NAMESPACE_PREFIX = 'gym_brand:';
const VENUE_SOURCE_ID_NAMESPACE_PREFIX = 'gym_venue_source:';
const VENUE_HISTORY_ID_NAMESPACE_PREFIX = 'gym_venue_history:';

function log(msg) {
  console.log(`[seed-sql] ${msg}`);
}

// --- SQL literal helpers (all values pass through here; no string
// concatenation of untrusted content anywhere else in this file) --------
function sqlNull() {
  return 'NULL';
}

function sqlString(v) {
  if (v === null || v === undefined) return sqlNull();
  return `'${String(v).replace(/'/g, "''")}'`;
}

function sqlUuid(v) {
  if (v === null || v === undefined) return sqlNull();
  return `${sqlString(v)}::uuid`;
}

function sqlNumber(v) {
  if (v === null || v === undefined || v === '' || Number.isNaN(Number(v))) return sqlNull();
  return String(Number(v));
}

function sqlInt(v) {
  if (v === null || v === undefined || v === '') return sqlNull();
  const n = Number(v);
  return Number.isFinite(n) ? String(Math.round(n)) : sqlNull();
}

function sqlTextArray(arr) {
  if (!Array.isArray(arr) || arr.length === 0) return sqlNull();
  return `ARRAY[${arr.map((v) => sqlString(v)).join(',')}]::text[]`;
}

function sqlTimestamptz(iso) {
  if (!iso) return sqlNull();
  return `${sqlString(iso)}::timestamptz`;
}

function sqlNow() {
  return 'now()';
}

function sqlJsonb(obj) {
  if (obj === null || obj === undefined) return sqlNull();
  return `${sqlString(JSON.stringify(obj))}::jsonb`;
}

function sqlBoolean(v) {
  return v ? 'true' : 'false';
}

function pad3(n) {
  return String(n).padStart(3, '0');
}

function houseHeader({ filename, purpose, dependsOn, rollback }) {
  return `-- ${filename}
--
-- Purpose:           ${purpose}
--                    Part of the GD-24 gym directory seed
--                    (docs/gym-database-2026-09-06/20-BLUEPRINT.md, GD-24;
--                    rulings GD-18 to GD-24). Generated by
--                    scripts/gyms/seed-sql.mjs from data/gyms/*.
--
-- Applied locally:   N/A - no local SQLite table for the gym directory
--                    (data/gyms/* is a repo-versioned data asset, not
--                    synced through src/lib/database.js).
--
-- Applied remotely:  NO - WRITTEN, NOT APPLIED. This file waits for the
--                    founder's exact phrase "run against production" for
--                    the batch that contains it (supabase/README.md status
--                    block, CLAUDE.md section 2 "Database schema"). It
--                    depends on ${dependsOn}, which must be applied first.
--
-- Safe to re-run:    YES. Every statement is
--                    INSERT ... ON CONFLICT (id) DO UPDATE SET (the
--                    gym_postcode_sectors chunk conflicts on \`sector\`
--                    instead, its own primary key) - re-running changes
--                    nothing beyond refreshing each row to this file's
--                    values and \`updated_at\`.
--
-- Rollback:          ${rollback}
--
`;
}

function loadBrands() {
  if (!fs.existsSync(BRANDS_FILE)) return [];
  return JSON.parse(fs.readFileSync(BRANDS_FILE, 'utf8'));
}

function loadSectors() {
  if (!fs.existsSync(SECTORS_FILE)) return [];
  const lines = fs.readFileSync(SECTORS_FILE, 'utf8').split('\n').filter((l) => l.trim());
  if (lines.length === 0) return [];
  const header = parseCsvHeader(lines[0]);
  return lines.slice(1).map((l) => csvLineToRecord(header, l));
}

function brandId(key) {
  return uuidv5(`${BRAND_ID_NAMESPACE_PREFIX}${key}`);
}

function writeChunk(filePath, header, statements) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, `${header}${statements.join('\n')}\n`);
}

function chunkArray(arr, size) {
  const chunks = [];
  for (let i = 0; i < arr.length; i += size) chunks.push(arr.slice(i, i + size));
  return chunks;
}

// --- gym_brands ----------------------------------------------------------
function writeBrandsChunk(brands) {
  if (brands.length === 0) {
    log('brands: no data/gyms/brands.v1.json found - skipped');
    return 0;
  }
  const columns = ['id', 'key', 'name', 'aliases', 'wikidata_qid', 'website', 'kind'];
  const rows = brands.map((b) => {
    const id = brandId(b.key);
    const values = [
      sqlUuid(id),
      sqlString(b.key),
      sqlString(b.name),
      sqlTextArray(b.aliases),
      sqlString(b.wikidata_qid || null),
      sqlString(b.website || null),
      sqlString(b.kind),
    ];
    return `  (${values.join(', ')})`;
  });
  const updateSet = columns
    .filter((c) => c !== 'id')
    .map((c) => `${c} = excluded.${c}`)
    .join(', ');
  const statement = `INSERT INTO public.gym_brands (${columns.join(', ')}) VALUES\n${rows.join(',\n')}\nON CONFLICT (id) DO UPDATE SET ${updateSet};`;

  const header = houseHeader({
    filename: '000-brands.sql',
    purpose: `Seeds the ${brands.length}-row \`gym_brands\` table (GD-05).`,
    dependsOn: 'migrate_162 (gym directory schema)',
    rollback: `delete from public.gym_brands where id in (${brands.map((b) => `'${brandId(b.key)}'`).join(', ')});`,
  });
  writeChunk(path.join(OUT_DIR, '000-brands.sql'), header, [statement]);
  log(`gym_brands: wrote 000-brands.sql (${brands.length} rows)`);
  return brands.length;
}

// --- gym_postcode_sectors --------------------------------------------------
function writeSectorsChunks(sectors) {
  if (sectors.length === 0) {
    log('sectors: no data/gyms/postcode-sectors.v1.csv found - skipped');
    return 0;
  }
  const columns = ['sector', 'lat', 'lng', 'count', 'country', 'region_code', 'local_authority_code'];
  const chunks = chunkArray(sectors, CHUNK_SIZE);
  chunks.forEach((chunk, i) => {
    const rows = chunk.map((s) => {
      const values = [
        sqlString(s.sector),
        sqlNumber(s.lat),
        sqlNumber(s.lng),
        sqlInt(s.count),
        sqlString(s.country || null),
        sqlString(s.region_code || null),
        sqlString(s.local_authority_code || null),
      ];
      return `  (${values.join(', ')})`;
    });
    const updateSet = columns
      .filter((c) => c !== 'sector')
      .map((c) => `${c} = excluded.${c}`)
      .join(', ');
    const statement = `INSERT INTO public.gym_postcode_sectors (${columns.join(', ')}) VALUES\n${rows.join(',\n')}\nON CONFLICT (sector) DO UPDATE SET ${updateSet};`;

    const filename = `001-sectors-${pad3(i)}.sql`;
    const header = houseHeader({
      filename,
      purpose: `Seeds chunk ${i + 1}/${chunks.length} (${chunk.length} rows) of the ONSPD-derived \`gym_postcode_sectors\` table (GD-21/GD-24).`,
      dependsOn: 'migrate_162 (gym directory schema)',
      rollback: `delete from public.gym_postcode_sectors where sector in (${chunk.map((s) => `'${s.sector}'`).join(', ')});`,
    });
    writeChunk(path.join(OUT_DIR, filename), header, [statement]);
  });
  log(`gym_postcode_sectors: wrote ${chunks.length} chunk(s) (${sectors.length} rows)`);
  return sectors.length;
}

// --- gym_venues + gym_venue_sources ---------------------------------------
function venueSourceRows(venue) {
  return (venue.source_records || []).map((sr) => {
    // Task GD-24 instruction: a source row never carries the raw source
    // payload — only a small jsonb of source_status/source_dataset/licence.
    const payload = { source_status: sr.source_status ?? null, source_dataset: sr.source_dataset ?? null, licence: sr.licence ?? null };
    const id = uuidv5(`${VENUE_SOURCE_ID_NAMESPACE_PREFIX}${venue.id}|${sr.source}|${sr.source_record_id}`);
    return { id, venue_id: venue.id, sr, payload };
  });
}

function writeVenuesAndSourcesChunks(venues, carryNeedsReviewReason) {
  if (venues.length === 0) {
    log('venues: no data/gyms/uk-gyms.v1.jsonl.gz found - skipped');
    return { venueCount: 0, sourceCount: 0 };
  }

  const venueColumns = [
    'id',
    'display_name',
    'name',
    'brand_id',
    'venue_type',
    'status',
    'address_line',
    'town',
    'town_key',
    'local_authority_code',
    'local_authority_name',
    'region_code',
    'region_name',
    'country',
    'postcode',
    'outward',
    'sector',
    'lat',
    'lng',
    'coord_source',
    'geocell',
    'website',
    'phone',
    'facility_count',
    'parent_venue_id',
    'succeeded_by',
    'verification_status',
    // GD-26 point 4: `needs_review` (existing column) always carried;
    // `needs_review_reason` only when gym_venues actually has that column
    // (checked once in run() against migrate_162's own text) — otherwise
    // the reason goes to a gym_venue_history 'flag' row instead, see
    // writeVenueHistoryChunk below.
    'needs_review',
    ...(carryNeedsReviewReason ? ['needs_review_reason'] : []),
    'source_count',
    'tokens',
    'first_seen',
    'last_verified',
    'closed_at',
    'created_at',
    'updated_at',
  ];

  const venueChunks = chunkArray(venues, CHUNK_SIZE);
  venueChunks.forEach((chunk, i) => {
    const rows = chunk.map((v) => {
      const needsReview = Boolean(v.needs_review_reason);
      const values = [
        sqlUuid(v.id),
        sqlString(v.display_name),
        sqlString(v.name),
        v.brand_key ? sqlUuid(brandId(v.brand_key)) : sqlNull(),
        sqlString(v.venue_type),
        sqlString(v.status),
        sqlString(v.address_line),
        sqlString(v.town),
        sqlString(v.town_key),
        sqlString(v.local_authority_code),
        sqlString(v.local_authority_name),
        sqlString(v.region_code),
        sqlString(v.region_name),
        sqlString(v.country),
        sqlString(v.postcode),
        sqlString(v.outward),
        sqlString(v.sector),
        sqlNumber(v.lat),
        sqlNumber(v.lng),
        sqlString(v.coord_source),
        sqlString(v.geocell),
        sqlString(v.website),
        sqlString(v.phone),
        sqlInt(v.facility_count),
        v.parent_venue_id ? sqlUuid(v.parent_venue_id) : sqlNull(),
        v.succeeded_by ? sqlUuid(v.succeeded_by) : sqlNull(),
        sqlString(v.verification_status),
        sqlBoolean(needsReview),
        ...(carryNeedsReviewReason ? [sqlString(v.needs_review_reason)] : []),
        sqlInt(v.source_count),
        sqlTextArray(v.tokens),
        sqlTimestamptz(v.first_seen),
        sqlTimestamptz(v.last_verified),
        sqlTimestamptz(v.closed_at),
        sqlNow(),
        sqlNow(),
      ];
      return `  (${values.join(', ')})`;
    });
    const updateSet = venueColumns
      .filter((c) => c !== 'id' && c !== 'created_at')
      .map((c) => `${c} = excluded.${c}`)
      .join(', ');
    const statement = `INSERT INTO public.gym_venues (${venueColumns.join(', ')}) VALUES\n${rows.join(',\n')}\nON CONFLICT (id) DO UPDATE SET ${updateSet};`;

    const filename = `${pad3(100 + i)}-venues-${pad3(i)}.sql`;
    const header = houseHeader({
      filename,
      purpose: `Seeds chunk ${i + 1}/${venueChunks.length} (${chunk.length} rows) of the canonical \`gym_venues\` table (GD-04 site-not-facility rows, from data/gyms/uk-gyms.v1.jsonl.gz).`,
      dependsOn: 'migrate_162 (gym directory schema) and 000-brands.sql (brand_id foreign keys)',
      rollback: `delete from public.gym_venues where id in (${chunk.map((v) => `'${v.id}'`).join(', ')});`,
    });
    writeChunk(path.join(OUT_DIR, filename), header, [statement]);
  });
  log(`gym_venues: wrote ${venueChunks.length} chunk(s) (${venues.length} rows)`);

  const sourceColumns = [
    'id',
    'venue_id',
    'source',
    'source_record_id',
    'source_url',
    'source_name',
    'source_status',
    'source_updated_at',
    'retrieved_at',
    'payload',
  ];
  const allSourceRows = venues.flatMap((v) => venueSourceRows(v));
  const sourceChunks = chunkArray(allSourceRows, CHUNK_SIZE);
  sourceChunks.forEach((chunk, i) => {
    const rows = chunk.map(({ id, venue_id, sr, payload }) => {
      const values = [
        sqlUuid(id),
        sqlUuid(venue_id),
        sqlString(sr.source),
        sqlString(sr.source_record_id),
        sqlString(sr.source_url),
        sqlString(sr.source_name),
        sqlString(sr.source_status),
        sqlTimestamptz(sr.source_updated_at || null),
        sqlTimestamptz(sr.retrieved_at),
        sqlJsonb(payload),
      ];
      return `  (${values.join(', ')})`;
    });
    const updateSet = sourceColumns
      .filter((c) => c !== 'id')
      .map((c) => `${c} = excluded.${c}`)
      .join(', ');
    const statement = `INSERT INTO public.gym_venue_sources (${sourceColumns.join(', ')}) VALUES\n${rows.join(',\n')}\nON CONFLICT (id) DO UPDATE SET ${updateSet};`;

    const filename = `${pad3(200 + i)}-sources-${pad3(i)}.sql`;
    const header = houseHeader({
      filename,
      purpose: `Seeds chunk ${i + 1}/${sourceChunks.length} (${chunk.length} rows) of \`gym_venue_sources\` provenance rows (GD-02). Payload is deliberately NOT the raw source payload - only {source_status, source_dataset, licence}.`,
      dependsOn: 'migrate_162 (gym directory schema) and the venues chunks (venue_id foreign keys)',
      rollback: `delete from public.gym_venue_sources where id in (${chunk.map((r) => `'${r.id}'`).join(', ')});`,
    });
    writeChunk(path.join(OUT_DIR, filename), header, [statement]);
  });
  log(`gym_venue_sources: wrote ${sourceChunks.length} chunk(s) (${allSourceRows.length} rows)`);

  return { venueCount: venues.length, sourceCount: allSourceRows.length };
}

// --- gym_venue_history (GD-26 point 4 fallback) ---------------------------
// Only called when gym_venues has no `needs_review_reason` column: the
// reason goes here instead, as a 'flag' history row. `actor` is left NULL
// deliberately — this chunk is user-free, it never carries a person's id
// (the task's own instruction), unlike the app's own gym_venue_history
// writes (migrate_162's community/moderator RPCs), which record the
// acting user.
function writeVenueHistoryChunks(venues) {
  const flagged = venues.filter((v) => v.needs_review_reason);
  if (flagged.length === 0) {
    log('gym_venue_history: no operator_unconfirmed rows to flag - skipped');
    return 0;
  }

  const columns = ['id', 'venue_id', 'change', 'before', 'after', 'actor', 'created_at'];
  const chunks = chunkArray(flagged, CHUNK_SIZE);
  chunks.forEach((chunk, i) => {
    const rows = chunk.map((v) => {
      const id = uuidv5(`${VENUE_HISTORY_ID_NAMESPACE_PREFIX}${v.id}|${v.needs_review_reason}`);
      const values = [
        sqlUuid(id),
        sqlUuid(v.id),
        sqlString('flag'),
        sqlNull(),
        sqlJsonb({ reason: v.needs_review_reason }),
        sqlNull(),
        sqlNow(),
      ];
      return `  (${values.join(', ')})`;
    });
    const updateSet = columns
      .filter((c) => c !== 'id')
      .map((c) => `${c} = excluded.${c}`)
      .join(', ');
    const statement = `INSERT INTO public.gym_venue_history (${columns.join(', ')}) VALUES\n${rows.join(',\n')}\nON CONFLICT (id) DO UPDATE SET ${updateSet};`;

    const filename = `${pad3(300 + i)}-history-${pad3(i)}.sql`;
    const header = houseHeader({
      filename,
      purpose: `Seeds chunk ${i + 1}/${chunks.length} (${chunk.length} rows) of \`gym_venue_history\` 'flag' entries (GD-26 point 4 fallback: gym_venues has no needs_review_reason column, so the reason is recorded here instead; needs_review is still set true on the venue row). actor is NULL - user-free.`,
      dependsOn: 'migrate_162 (gym directory schema) and the venues chunks (venue_id foreign keys)',
      rollback: `delete from public.gym_venue_history where id in (${chunk.map((v) => `'${uuidv5(`${VENUE_HISTORY_ID_NAMESPACE_PREFIX}${v.id}|${v.needs_review_reason}`)}'`).join(', ')});`,
    });
    writeChunk(path.join(OUT_DIR, filename), header, [statement]);
  });
  log(`gym_venue_history: wrote ${chunks.length} chunk(s) (${flagged.length} rows, GD-26 not_in_operator_feed flags)`);
  return flagged.length;
}

function run() {
  fs.mkdirSync(OUT_DIR, { recursive: true });
  // Idempotent: clear any previously generated chunk files first, so a
  // shrinking row count (fewer venues/sectors on a re-run) never leaves a
  // stale extra chunk file behind.
  for (const f of fs.readdirSync(OUT_DIR)) {
    if (f.endsWith('.sql')) fs.rmSync(path.join(OUT_DIR, f));
  }

  const brands = loadBrands();
  const sectors = loadSectors();
  const venues = readJsonlGz(VENUES_FILE);

  // GD-26 point 4: decide once, from migrate_162's own text, whether
  // gym_venues already has BOTH verification_status and
  // needs_review_reason columns.
  const migrationSql = fs.existsSync(MIGRATION_FILE) ? fs.readFileSync(MIGRATION_FILE, 'utf8') : '';
  const carryNeedsReviewReason = gymVenuesHasAllColumns(migrationSql, ['verification_status', 'needs_review_reason']);
  log(
    `GD-26: gym_venues needs_review_reason column ${carryNeedsReviewReason ? 'present' : 'ABSENT'} in migrate_162 - ` +
      `${carryNeedsReviewReason ? 'carrying it through directly' : 'falling back to needs_review + gym_venue_history flag rows'}`,
  );

  const brandCount = writeBrandsChunk(brands);
  const sectorCount = writeSectorsChunks(sectors);
  const { venueCount, sourceCount } = writeVenuesAndSourcesChunks(venues, carryNeedsReviewReason);
  const historyCount = carryNeedsReviewReason ? 0 : writeVenueHistoryChunks(venues);

  log(
    `done: ${brandCount} brands, ${sectorCount} sectors, ${venueCount} venues, ${sourceCount} source rows, ` +
      `${historyCount} history flag row(s) -> ${OUT_DIR} (WRITTEN, NOT APPLIED — nothing here runs against Supabase)`,
  );
}

run();
