// GENERATED from the mobile app exercise library (src/lib/seedExercises.js RAW).
// Each canonical exercise: its name, primary muscle and secondary muscles. The
// web resolves a workout_set.exercise_id to one of these via canonicalExerciseId
// (the same deterministic name-hash the app uses), so no exercise library needs
// to live in the cloud. Regenerate if the mobile RAW list changes.
//
// Do not hand-edit. 449 exercises.

export interface LibraryExercise {
  name: string;
  primary: string;
  secondary: string[];
}

export const EXERCISE_LIBRARY: readonly LibraryExercise[] = [
  { name: "Barbell Bench Press", primary: "chest", secondary: ["triceps", "front_delts"] },
  { name: "Incline Barbell Bench Press", primary: "chest", secondary: ["triceps", "front_delts"] },
  { name: "Decline Barbell Bench Press", primary: "chest", secondary: ["triceps"] },
  { name: "Dumbbell Bench Press", primary: "chest", secondary: ["triceps", "front_delts"] },
  { name: "Incline Dumbbell Press", primary: "chest", secondary: ["triceps", "front_delts"] },
  { name: "Decline Dumbbell Press", primary: "chest", secondary: ["triceps"] },
  { name: "Cable Fly (Low to High)", primary: "chest", secondary: [] },
  { name: "Cable Crossover (High to Low)", primary: "chest", secondary: [] },
  { name: "Dumbbell Fly", primary: "chest", secondary: [] },
  { name: "Incline Dumbbell Fly", primary: "chest", secondary: [] },
  { name: "Decline Dumbbell Fly", primary: "chest", secondary: [] },
  { name: "Pec Deck (Machine Fly)", primary: "chest", secondary: [] },
  { name: "Machine Chest Press", primary: "chest", secondary: ["triceps", "front_delts"] },
  { name: "Incline Machine Press", primary: "chest", secondary: ["triceps", "front_delts"] },
  { name: "Decline Machine Press", primary: "chest", secondary: ["triceps"] },
  { name: "Weighted Dips (Chest)", primary: "chest", secondary: ["triceps", "front_delts"] },
  { name: "Push-Up", primary: "chest", secondary: ["triceps", "front_delts"] },
  { name: "Wide-Grip Push-Up", primary: "chest", secondary: ["triceps", "front_delts"] },
  { name: "Decline Push-Up", primary: "chest", secondary: ["triceps", "front_delts"] },
  { name: "Ring Push-Up", primary: "chest", secondary: ["triceps", "front_delts"] },
  { name: "Landmine Press", primary: "chest", secondary: ["front_delts"] },
  { name: "Smith Machine Bench Press", primary: "chest", secondary: ["triceps", "front_delts"] },
  { name: "Incline Smith Machine Press", primary: "chest", secondary: ["triceps", "front_delts"] },
  { name: "Cable Fly (Neutral)", primary: "chest", secondary: [] },
  { name: "Cable Fly (Chest Height)", primary: "chest", secondary: [] },
  { name: "High Cable Fly", primary: "chest", secondary: [] },
  { name: "Low Cable Fly", primary: "chest", secondary: [] },
  { name: "Incline Cable Fly", primary: "chest", secondary: [] },
  { name: "Svend Press", primary: "chest", secondary: [] },
  { name: "Dumbbell Pullover", primary: "chest", secondary: ["back"] },
  { name: "Hammer Strength Chest Press", primary: "chest", secondary: ["triceps", "front_delts"] },
  { name: "Reverse-Grip Bench Press", primary: "chest", secondary: ["triceps", "front_delts"] },
  { name: "Dumbbell Squeeze Press", primary: "chest", secondary: ["triceps"] },
  { name: "Cable Fly (High to Low)", primary: "chest", secondary: [] },
  { name: "Dumbbell Pullover (Chest)", primary: "chest", secondary: ["back"] },
  { name: "Barbell Row (Bent Over)", primary: "back", secondary: ["biceps", "rear_delts"] },
  { name: "Barbell Row (Supinated)", primary: "back", secondary: ["biceps"] },
  { name: "Dumbbell Row", primary: "back", secondary: ["biceps"] },
  { name: "T-Bar Row", primary: "back", secondary: ["biceps"] },
  { name: "Chest-Supported T-Bar Row", primary: "back", secondary: ["biceps"] },
  { name: "Seated Cable Row", primary: "back", secondary: ["biceps"] },
  { name: "Lat Pulldown (Wide Grip)", primary: "back", secondary: ["biceps"] },
  { name: "Lat Pulldown (Close Grip)", primary: "back", secondary: ["biceps"] },
  { name: "Lat Pulldown (Neutral Grip)", primary: "back", secondary: ["biceps"] },
  { name: "Pull-Up", primary: "back", secondary: ["biceps"] },
  { name: "Weighted Pull-Up", primary: "back", secondary: ["biceps"] },
  { name: "Chin-Up", primary: "back", secondary: ["biceps"] },
  { name: "Neutral Grip Pull-Up", primary: "back", secondary: ["biceps"] },
  { name: "Assisted Pull-Up", primary: "back", secondary: ["biceps"] },
  { name: "Machine Row (Chest Supported)", primary: "back", secondary: ["biceps"] },
  { name: "Cable Straight-Arm Pulldown", primary: "back", secondary: [] },
  { name: "Landmine Row", primary: "back", secondary: ["biceps"] },
  { name: "Conventional Deadlift", primary: "back", secondary: ["quads", "glutes", "hamstrings"] },
  { name: "Sumo Deadlift", primary: "back", secondary: ["quads", "glutes", "hamstrings"] },
  { name: "Rack Pull", primary: "back", secondary: ["glutes"] },
  { name: "Snatch Grip Deadlift", primary: "back", secondary: ["glutes", "hamstrings"] },
  { name: "Deficit Deadlift", primary: "back", secondary: ["quads", "glutes", "hamstrings"] },
  { name: "Cable High Row", primary: "back", secondary: ["biceps"] },
  { name: "Single-Arm Cable Row", primary: "back", secondary: ["biceps"] },
  { name: "Trap Bar Deadlift", primary: "back", secondary: ["quads", "glutes", "hamstrings"] },
  { name: "Pendlay Row", primary: "back", secondary: ["biceps"] },
  { name: "Inverted Row", primary: "back", secondary: ["biceps"] },
  { name: "Cable Lat Pullover", primary: "back", secondary: [] },
  { name: "Single-Arm Lat Pulldown", primary: "back", secondary: ["biceps"] },
  { name: "Meadows Row", primary: "back", secondary: ["biceps"] },
  { name: "Kroc Row", primary: "back", secondary: ["biceps"] },
  { name: "Seal Row", primary: "back", secondary: ["biceps"] },
  { name: "Chest-Supported Row (Dumbbell)", primary: "back", secondary: ["biceps"] },
  { name: "Seated Machine Row (Wide)", primary: "back", secondary: ["biceps"] },
  { name: "Face Pull (Rope)", primary: "back", secondary: ["rear_delts", "traps"] },
  { name: "Helms Row", primary: "back", secondary: ["biceps"] },
  { name: "Hyperextension (Back Extension)", primary: "back", secondary: ["glutes", "hamstrings"] },
  { name: "Good Morning (Barbell)", primary: "hamstrings", secondary: ["glutes", "back"] },
  { name: "Reverse Hyperextension", primary: "back", secondary: ["glutes", "hamstrings"] },
  { name: "Chest-Supported Row (Barbell)", primary: "back", secondary: ["biceps"] },
  { name: "Cable Row (Wide Grip)", primary: "back", secondary: ["biceps", "rear_delts"] },
  { name: "Machine Row (Hammer Strength)", primary: "back", secondary: ["biceps"] },
  { name: "TRX Row", primary: "back", secondary: ["biceps"] },
  { name: "Back Extension (Weighted)", primary: "back", secondary: ["glutes", "hamstrings"] },
  { name: "Barbell Overhead Press", primary: "front_delts", secondary: ["triceps", "side_delts"] },
  { name: "Dumbbell Shoulder Press", primary: "front_delts", secondary: ["triceps", "side_delts"] },
  { name: "Arnold Press", primary: "front_delts", secondary: ["triceps", "side_delts"] },
  { name: "Seated Dumbbell Press", primary: "front_delts", secondary: ["triceps", "side_delts"] },
  { name: "Z-Press", primary: "front_delts", secondary: ["triceps", "side_delts"] },
  { name: "Push Press", primary: "front_delts", secondary: ["triceps", "side_delts"] },
  { name: "Dumbbell Front Raise", primary: "front_delts", secondary: [] },
  { name: "Cable Front Raise", primary: "front_delts", secondary: [] },
  { name: "Dumbbell Lateral Raise", primary: "side_delts", secondary: [] },
  { name: "Cable Lateral Raise", primary: "side_delts", secondary: [] },
  { name: "Machine Lateral Raise", primary: "side_delts", secondary: [] },
  { name: "Leaning Lateral Raise", primary: "side_delts", secondary: [] },
  { name: "Landmine Lateral Raise", primary: "side_delts", secondary: [] },
  { name: "Seated Lateral Raise", primary: "side_delts", secondary: [] },
  { name: "Upright Row", primary: "side_delts", secondary: ["biceps", "traps"] },
  { name: "Machine Shoulder Press", primary: "side_delts", secondary: ["triceps", "front_delts"] },
  { name: "Viking Press", primary: "side_delts", secondary: ["triceps", "front_delts"] },
  { name: "Leaning Cable Lateral Raise", primary: "side_delts", secondary: [] },
  { name: "Plate Lateral Raise", primary: "side_delts", secondary: [] },
  { name: "Cable Upright Row", primary: "side_delts", secondary: ["biceps", "traps"] },
  { name: "Dumbbell Y-Raise", primary: "side_delts", secondary: ["rear_delts", "traps"] },
  { name: "Dumbbell Rear Delt Fly", primary: "rear_delts", secondary: ["back"] },
  { name: "Cable Rear Delt Fly", primary: "rear_delts", secondary: ["back"] },
  { name: "Machine Rear Delt Fly", primary: "rear_delts", secondary: ["back"] },
  { name: "Reverse Pec Deck", primary: "rear_delts", secondary: ["back"] },
  { name: "Cable Y-Raise (Prone)", primary: "rear_delts", secondary: ["back"] },
  { name: "Face Pull", primary: "rear_delts", secondary: ["back", "traps"] },
  { name: "Dumbbell Side-Lying Rear Delt", primary: "rear_delts", secondary: [] },
  { name: "W-Raise", primary: "rear_delts", secondary: ["back", "traps"] },
  { name: "YTW", primary: "rear_delts", secondary: ["back", "traps"] },
  { name: "Lying Rear Delt Row", primary: "rear_delts", secondary: ["back"] },
  { name: "Cable Face Pull", primary: "rear_delts", secondary: ["back", "traps"] },
  { name: "Cable Face Pull (Rope)", primary: "rear_delts", secondary: ["back", "traps"] },
  { name: "Bent-Over Cable Rear Delt Fly", primary: "rear_delts", secondary: ["back"] },
  { name: "Prone Incline Y-Raise", primary: "rear_delts", secondary: ["back", "traps"] },
  { name: "Prone Incline T-Raise", primary: "rear_delts", secondary: ["back", "traps"] },
  { name: "Seated Rear Delt Machine", primary: "rear_delts", secondary: ["back"] },
  { name: "Barbell Curl", primary: "biceps", secondary: [] },
  { name: "EZ Bar Curl", primary: "biceps", secondary: [] },
  { name: "Dumbbell Curl", primary: "biceps", secondary: [] },
  { name: "Hammer Curl", primary: "biceps", secondary: ["forearms"] },
  { name: "Incline Dumbbell Curl", primary: "biceps", secondary: [] },
  { name: "Preacher Curl (Barbell)", primary: "biceps", secondary: [] },
  { name: "Preacher Curl (Dumbbell)", primary: "biceps", secondary: [] },
  { name: "Preacher Curl (EZ Bar)", primary: "biceps", secondary: [] },
  { name: "Cable Curl", primary: "biceps", secondary: [] },
  { name: "Cable Hammer Curl (Rope)", primary: "biceps", secondary: ["forearms"] },
  { name: "Machine Curl", primary: "biceps", secondary: [] },
  { name: "Concentration Curl", primary: "biceps", secondary: [] },
  { name: "Zottman Curl", primary: "biceps", secondary: ["forearms"] },
  { name: "Spider Curl", primary: "biceps", secondary: [] },
  { name: "Cross-Body Hammer Curl", primary: "biceps", secondary: ["forearms"] },
  { name: "Prone Incline Curl", primary: "biceps", secondary: [] },
  { name: "Reverse Curl", primary: "biceps", secondary: ["forearms"] },
  { name: "Cable Reverse Curl", primary: "biceps", secondary: ["forearms"] },
  { name: "EZ Bar Preacher Curl", primary: "biceps", secondary: [] },
  { name: "Cable Rope Hammer Curl", primary: "biceps", secondary: ["forearms"] },
  { name: "Bayesian Curl", primary: "biceps", secondary: [] },
  { name: "Waiter Curl", primary: "biceps", secondary: [] },
  { name: "TRX Curl", primary: "biceps", secondary: [] },
  { name: "Close-Grip Bench Press", primary: "triceps", secondary: ["chest", "front_delts"] },
  { name: "EZ Bar Skull Crusher", primary: "triceps", secondary: [] },
  { name: "Dumbbell Skull Crusher", primary: "triceps", secondary: [] },
  { name: "Decline Skull Crusher", primary: "triceps", secondary: [] },
  { name: "Tricep Pushdown (Rope)", primary: "triceps", secondary: [] },
  { name: "Tricep Pushdown (Bar)", primary: "triceps", secondary: [] },
  { name: "Cable Pushdown (Straight Bar)", primary: "triceps", secondary: [] },
  { name: "Rope Pushdown", primary: "triceps", secondary: [] },
  { name: "Overhead Cable Tricep Extension", primary: "triceps", secondary: [] },
  { name: "Dumbbell Overhead Tricep Extension", primary: "triceps", secondary: [] },
  { name: "Overhead Dumbbell Extension", primary: "triceps", secondary: [] },
  { name: "Weighted Dips (Triceps)", primary: "triceps", secondary: ["chest", "front_delts"] },
  { name: "Bench Dip", primary: "triceps", secondary: ["chest", "front_delts"] },
  { name: "Tricep Kickback", primary: "triceps", secondary: [] },
  { name: "Diamond Push-Up", primary: "triceps", secondary: ["chest"] },
  { name: "JM Press", primary: "triceps", secondary: ["chest"] },
  { name: "Tate Press", primary: "triceps", secondary: [] },
  { name: "Lying Tricep Extension", primary: "triceps", secondary: [] },
  { name: "Machine Tricep Extension", primary: "triceps", secondary: [] },
  { name: "Single Arm Cable Extension", primary: "triceps", secondary: [] },
  { name: "Board Press", primary: "triceps", secondary: ["chest"] },
  { name: "Close-Grip Floor Press", primary: "triceps", secondary: ["chest"] },
  { name: "Reverse Grip Cable Pushdown", primary: "triceps", secondary: [] },
  { name: "Tricep Dip (Parallel Bars)", primary: "triceps", secondary: ["chest", "front_delts"] },
  { name: "Cable Overhead Tricep Extension", primary: "triceps", secondary: [] },
  { name: "Barbell Back Squat", primary: "quads", secondary: ["glutes", "hamstrings"] },
  { name: "Barbell Front Squat", primary: "quads", secondary: ["glutes"] },
  { name: "Hack Squat Machine", primary: "quads", secondary: ["glutes"] },
  { name: "Leg Press", primary: "quads", secondary: ["glutes", "hamstrings"] },
  { name: "Bulgarian Split Squat", primary: "quads", secondary: ["glutes"] },
  { name: "Leg Extension", primary: "quads", secondary: [] },
  { name: "Sissy Squat", primary: "quads", secondary: [] },
  { name: "Goblet Squat", primary: "quads", secondary: ["glutes"] },
  { name: "Dumbbell Lunge", primary: "quads", secondary: ["glutes"] },
  { name: "Walking Lunge", primary: "quads", secondary: ["glutes", "hamstrings"] },
  { name: "Barbell Lunge", primary: "quads", secondary: ["glutes"] },
  { name: "Step-Up (Dumbbell)", primary: "quads", secondary: ["glutes"] },
  { name: "Step-Up (Barbell)", primary: "quads", secondary: ["glutes"] },
  { name: "Wall Sit", primary: "quads", secondary: [] },
  { name: "Cyclist Squat", primary: "quads", secondary: ["glutes"] },
  { name: "Smith Machine Squat", primary: "quads", secondary: ["glutes"] },
  { name: "Box Squat", primary: "quads", secondary: ["glutes", "hamstrings"] },
  { name: "Pause Squat", primary: "quads", secondary: ["glutes"] },
  { name: "Heel-Elevated Squat", primary: "quads", secondary: ["glutes"] },
  { name: "Single Leg Press", primary: "quads", secondary: ["glutes"] },
  { name: "Pendulum Squat", primary: "quads", secondary: ["glutes"] },
  { name: "Spanish Squat", primary: "quads", secondary: [] },
  { name: "Leg Press (Narrow Stance)", primary: "quads", secondary: ["glutes"] },
  { name: "Sumo Squat", primary: "quads", secondary: ["glutes", "hamstrings"] },
  { name: "Safety Bar Squat", primary: "quads", secondary: ["glutes", "hamstrings"] },
  { name: "Front Squat (Dumbbell)", primary: "quads", secondary: ["glutes"] },
  { name: "Split Squat", primary: "quads", secondary: ["glutes"] },
  { name: "Reverse Lunge", primary: "quads", secondary: ["glutes"] },
  { name: "Curtsy Lunge", primary: "quads", secondary: ["glutes"] },
  { name: "Leg Press (High Foot)", primary: "quads", secondary: ["glutes", "hamstrings"] },
  { name: "Cycling (Stationary)", primary: "quads", secondary: ["calves", "glutes"] },
  { name: "Terminal Knee Extension", primary: "quads", secondary: [] },
  { name: "Romanian Deadlift", primary: "hamstrings", secondary: ["glutes", "back"] },
  { name: "Romanian Deadlift (Barbell)", primary: "hamstrings", secondary: ["glutes", "back"] },
  { name: "Romanian Deadlift (Dumbbell)", primary: "hamstrings", secondary: ["glutes"] },
  { name: "Stiff-Leg Deadlift", primary: "hamstrings", secondary: ["back", "glutes"] },
  { name: "Nordic Curl", primary: "hamstrings", secondary: [] },
  { name: "Nordic Hamstring Curl", primary: "hamstrings", secondary: [] },
  { name: "Lying Leg Curl", primary: "hamstrings", secondary: [] },
  { name: "Seated Leg Curl", primary: "hamstrings", secondary: [] },
  { name: "Standing Leg Curl", primary: "hamstrings", secondary: [] },
  { name: "Leg Curl (Cable)", primary: "hamstrings", secondary: [] },
  { name: "Good Morning", primary: "hamstrings", secondary: ["back", "glutes"] },
  { name: "Glute Ham Raise", primary: "hamstrings", secondary: ["glutes"] },
  { name: "Single-Leg Romanian Deadlift", primary: "hamstrings", secondary: ["glutes"] },
  { name: "Single-Leg Romanian Deadlift (DB)", primary: "hamstrings", secondary: ["glutes"] },
  { name: "B-Stance Romanian Deadlift", primary: "hamstrings", secondary: ["glutes"] },
  { name: "Swiss Ball Leg Curl", primary: "hamstrings", secondary: ["glutes"] },
  { name: "Cable Pull-Through", primary: "glutes", secondary: ["hamstrings"] },
  { name: "Kettlebell Swing", primary: "hamstrings", secondary: ["glutes", "back"] },
  { name: "Deadlift (Conventional)", primary: "hamstrings", secondary: ["back", "glutes", "quads"] },
  { name: "Deadlift (Sumo)", primary: "hamstrings", secondary: ["back", "glutes", "quads"] },
  { name: "Trap Bar Deadlift (Hamstring)", primary: "hamstrings", secondary: ["back", "glutes"] },
  { name: "Prone Leg Curl", primary: "hamstrings", secondary: [] },
  { name: "Dumbbell Single-Leg RDL", primary: "hamstrings", secondary: ["glutes"] },
  { name: "Barbell Hip Thrust", primary: "glutes", secondary: ["hamstrings", "quads"] },
  { name: "Dumbbell Hip Thrust", primary: "glutes", secondary: ["hamstrings"] },
  { name: "Smith Machine Hip Thrust", primary: "glutes", secondary: ["hamstrings"] },
  { name: "Machine Hip Thrust", primary: "glutes", secondary: ["hamstrings"] },
  { name: "Glute Bridge", primary: "glutes", secondary: ["hamstrings"] },
  { name: "Single Leg Hip Thrust", primary: "glutes", secondary: ["hamstrings"] },
  { name: "Frog Pump", primary: "glutes", secondary: [] },
  { name: "Cable Kickback", primary: "glutes", secondary: [] },
  { name: "Donkey Kick", primary: "glutes", secondary: [] },
  { name: "Abduction Machine", primary: "glutes", secondary: [] },
  { name: "Cable Hip Abduction", primary: "glutes", secondary: [] },
  { name: "Step-Up (Glute Focus)", primary: "glutes", secondary: ["quads"] },
  { name: "Sumo Squat (Glute Focus)", primary: "glutes", secondary: ["hamstrings"] },
  { name: "Nordic Glute Curl", primary: "glutes", secondary: ["hamstrings"] },
  { name: "45-Degree Hip Extension", primary: "glutes", secondary: ["hamstrings", "back"] },
  { name: "Reverse Hyperextension (Glute)", primary: "glutes", secondary: ["hamstrings"] },
  { name: "Sumo Deadlift (Glute Focus)", primary: "glutes", secondary: ["hamstrings", "quads"] },
  { name: "Sumo Deadlift (Wide Stance)", primary: "glutes", secondary: ["hamstrings", "quads"] },
  { name: "Cable Donkey Kickback", primary: "glutes", secondary: [] },
  { name: "Donkey Kickback (Machine)", primary: "glutes", secondary: [] },
  { name: "Walking Lunge (Glute Focus)", primary: "glutes", secondary: ["quads", "hamstrings"] },
  { name: "Curtsy Lunge (Glute Focus)", primary: "glutes", secondary: ["quads"] },
  { name: "Kickstand Hip Thrust", primary: "glutes", secondary: ["hamstrings"] },
  { name: "Cable Pull-Through (Glute)", primary: "glutes", secondary: ["hamstrings"] },
  { name: "Romanian Deadlift (Glute)", primary: "glutes", secondary: ["hamstrings", "back"] },
  { name: "Standing Calf Raise (Machine)", primary: "calves", secondary: [] },
  { name: "Standing Calf Raise (Barbell)", primary: "calves", secondary: [] },
  { name: "Seated Calf Raise", primary: "calves", secondary: [] },
  { name: "Seated Machine Calf Raise", primary: "calves", secondary: [] },
  { name: "Seated Dumbbell Calf Raise", primary: "calves", secondary: [] },
  { name: "Leg Press Calf Raise", primary: "calves", secondary: [] },
  { name: "Donkey Calf Raise", primary: "calves", secondary: [] },
  { name: "Single-Leg Calf Raise (Bodyweight)", primary: "calves", secondary: [] },
  { name: "Dumbbell Calf Raise (Standing)", primary: "calves", secondary: [] },
  { name: "Smith Machine Calf Raise", primary: "calves", secondary: [] },
  { name: "Calf Raise on Steps", primary: "calves", secondary: [] },
  { name: "Box Jump", primary: "calves", secondary: ["quads", "glutes"] },
  { name: "Single-Leg Calf Raise (Dumbbell)", primary: "calves", secondary: [] },
  { name: "Calf Raise on Leg Press Sled", primary: "calves", secondary: [] },
  { name: "Standing Calf Raise (Bodyweight)", primary: "calves", secondary: [] },
  { name: "Tibialis Raise (Wall)", primary: "tibialis", secondary: [] },
  { name: "Tibialis Raise (Slant Board)", primary: "tibialis", secondary: [] },
  { name: "Toe Walk", primary: "tibialis", secondary: ["calves"] },
  { name: "Cable Crunch", primary: "abs", secondary: [] },
  { name: "Hanging Leg Raise", primary: "abs", secondary: [] },
  { name: "Plank", primary: "abs", secondary: [] },
  { name: "Side Plank", primary: "abs", secondary: [] },
  { name: "Ab Rollout", primary: "abs", secondary: [] },
  { name: "Ab Wheel Rollout", primary: "abs", secondary: [] },
  { name: "Decline Crunch", primary: "abs", secondary: [] },
  { name: "Russian Twist", primary: "abs", secondary: [] },
  { name: "Pallof Press", primary: "abs", secondary: [] },
  { name: "Landmine Twist", primary: "abs", secondary: [] },
  { name: "Landmine Rotation", primary: "abs", secondary: [] },
  { name: "Bicycle Crunch", primary: "abs", secondary: [] },
  { name: "Crunch", primary: "abs", secondary: [] },
  { name: "Reverse Crunch", primary: "abs", secondary: [] },
  { name: "Leg Raise", primary: "abs", secondary: [] },
  { name: "Leg Raise (Flat Bench)", primary: "abs", secondary: [] },
  { name: "Dragon Flag", primary: "abs", secondary: [] },
  { name: "V-Up", primary: "abs", secondary: [] },
  { name: "Sit-Up", primary: "abs", secondary: [] },
  { name: "Cable Woodchop", primary: "abs", secondary: [] },
  { name: "Machine Crunch", primary: "abs", secondary: [] },
  { name: "Dead Bug", primary: "abs", secondary: [] },
  { name: "Hollow Body Hold", primary: "abs", secondary: [] },
  { name: "Stir the Pot", primary: "abs", secondary: [] },
  { name: "Hanging Knee Raise", primary: "abs", secondary: [] },
  { name: "Cable Woodchop (High to Low)", primary: "abs", secondary: [] },
  { name: "Cable Woodchop (Low to High)", primary: "abs", secondary: [] },
  { name: "Ab Wheel (Kneeling)", primary: "abs", secondary: [] },
  { name: "Weighted Sit-Up", primary: "abs", secondary: [] },
  { name: "Toe-to-Bar", primary: "abs", secondary: [] },
  { name: "L-Sit Hold", primary: "abs", secondary: ["triceps"] },
  { name: "Suitcase Carry", primary: "abs", secondary: ["traps", "forearms"] },
  { name: "Pallof Press (Kneeling)", primary: "abs", secondary: [] },
  { name: "Copenhagen Plank", primary: "abs", secondary: ["glutes"] },
  { name: "Barbell Shrug", primary: "traps", secondary: [] },
  { name: "Dumbbell Shrug", primary: "traps", secondary: [] },
  { name: "Cable Shrug", primary: "traps", secondary: [] },
  { name: "Smith Machine Shrug", primary: "traps", secondary: [] },
  { name: "Hex Bar Shrug", primary: "traps", secondary: [] },
  { name: "Behind-the-Back Barbell Shrug", primary: "traps", secondary: [] },
  { name: "Farmer's Walk", primary: "traps", secondary: ["forearms", "abs"] },
  { name: "Power Clean", primary: "traps", secondary: ["quads", "glutes", "back"] },
  { name: "Rack Pull (Traps)", primary: "traps", secondary: ["back"] },
  { name: "Face Pull (Traps)", primary: "traps", secondary: ["rear_delts"] },
  { name: "Incline Shrug", primary: "traps", secondary: [] },
  { name: "Snatch Grip Shrug", primary: "traps", secondary: [] },
  { name: "Keg Carry", primary: "traps", secondary: ["forearms", "abs"] },
  { name: "Barbell Wrist Curl", primary: "forearms", secondary: [] },
  { name: "Reverse Wrist Curl", primary: "forearms", secondary: [] },
  { name: "Dumbbell Wrist Curl", primary: "forearms", secondary: [] },
  { name: "Plate Pinch", primary: "forearms", secondary: [] },
  { name: "Dead Hang", primary: "forearms", secondary: ["back"] },
  { name: "Thick Bar Curl", primary: "forearms", secondary: ["biceps"] },
  { name: "Cable Reverse Curl (Forearms)", primary: "forearms", secondary: ["biceps"] },
  { name: "Farmer Walk (Forearms)", primary: "forearms", secondary: ["traps"] },
  { name: "Towel Pull-Up", primary: "forearms", secondary: ["back", "biceps"] },
  { name: "Fat Grip Curl", primary: "forearms", secondary: ["biceps"] },
  { name: "Hand Gripper", primary: "forearms", secondary: [] },
  { name: "Rice Bucket", primary: "forearms", secondary: [] },
  { name: "Pinch Grip Carry", primary: "forearms", secondary: ["traps"] },
  { name: "Cable Wrist Curl", primary: "forearms", secondary: [] },
  { name: "Cable Reverse Wrist Curl", primary: "forearms", secondary: [] },
  { name: "Neck Flexion (Machine)", primary: "neck", secondary: [] },
  { name: "Neck Extension (Machine)", primary: "neck", secondary: [] },
  { name: "Neck Lateral Flexion", primary: "neck", secondary: [] },
  { name: "Neck Curl", primary: "neck", secondary: [] },
  { name: "Neck Bridge", primary: "neck", secondary: ["traps"] },
  { name: "Plate Neck Curl", primary: "neck", secondary: [] },
  { name: "Plate Neck Extension", primary: "neck", secondary: ["traps"] },
  { name: "Neck Harness Flexion", primary: "neck", secondary: [] },
  { name: "Neck Harness Extension", primary: "neck", secondary: ["traps"] },
  { name: "Manual Resistance Neck Flexion", primary: "neck", secondary: [] },
  { name: "Manual Resistance Neck Extension", primary: "neck", secondary: ["traps"] },
  { name: "Neck Rotation (Resistance)", primary: "neck", secondary: [] },
  { name: "Sled Push", primary: "quads", secondary: ["glutes", "calves"] },
  { name: "Sled Pull", primary: "hamstrings", secondary: ["glutes"] },
  { name: "Prowler Drag", primary: "hamstrings", secondary: ["glutes", "quads"] },
  { name: "Battle Ropes", primary: "front_delts", secondary: ["side_delts", "abs"] },
  { name: "Assault Bike", primary: "quads", secondary: ["calves", "glutes"] },
  { name: "Tyre Flip", primary: "back", secondary: ["glutes", "quads"] },
  { name: "Kettlebell Snatch", primary: "back", secondary: ["glutes", "hamstrings"] },
  { name: "Kettlebell Clean and Press", primary: "front_delts", secondary: ["glutes", "traps"] },
  { name: "Jump Squat", primary: "quads", secondary: ["glutes", "calves"] },
  { name: "Broad Jump", primary: "quads", secondary: ["glutes", "calves"] },
  { name: "Depth Jump", primary: "quads", secondary: ["calves", "glutes"] },
  { name: "Stair Running", primary: "quads", secondary: ["glutes", "calves"] },
  { name: "Clean Pull", primary: "traps", secondary: ["back", "glutes", "quads"] },
  { name: "Barbell Good Morning", primary: "hamstrings", secondary: ["back", "glutes"] },
  { name: "Zercher Squat", primary: "quads", secondary: ["glutes", "back"] },
  { name: "Anderson Squat", primary: "quads", secondary: ["glutes"] },
  { name: "Pin Squat", primary: "quads", secondary: ["glutes"] },
  { name: "Hatfield Squat", primary: "quads", secondary: ["glutes", "hamstrings"] },
  { name: "Cambered Bar Squat", primary: "quads", secondary: ["glutes", "back"] },
  { name: "SSB Squat", primary: "quads", secondary: ["glutes"] },
  { name: "Jefferson Curl", primary: "hamstrings", secondary: ["back"] },
  { name: "Stiff-Leg Deadlift (Dumbbell)", primary: "hamstrings", secondary: ["back", "glutes"] },
  { name: "Serratus Punch", primary: "abs", secondary: ["front_delts"] },
  { name: "Kneeling Cable Crunch", primary: "abs", secondary: [] },
  { name: "Exercise Ball Crunch", primary: "abs", secondary: [] },
  { name: "Mountain Climber", primary: "abs", secondary: ["quads", "front_delts"] },
  { name: "Plank Row", primary: "abs", secondary: ["back", "biceps"] },
  { name: "Bear Crawl", primary: "abs", secondary: ["front_delts", "quads"] },
  { name: "Kneeling Ab Rollout", primary: "abs", secondary: [] },
  { name: "Dumbbell Side Bend", primary: "abs", secondary: [] },
  { name: "Cable Side Bend", primary: "abs", secondary: [] },
  { name: "Windmill", primary: "abs", secondary: ["glutes", "side_delts"] },
  { name: "Turkish Get-Up", primary: "abs", secondary: ["glutes", "front_delts"] },
  { name: "Close-Grip Push-Up", primary: "chest", secondary: ["triceps"] },
  { name: "Archer Push-Up", primary: "chest", secondary: ["triceps", "front_delts"] },
  { name: "Single-Arm Push-Up", primary: "chest", secondary: ["triceps"] },
  { name: "Cable Chest Press (Standing)", primary: "chest", secondary: ["triceps", "front_delts"] },
  { name: "Smith Machine Incline Press", primary: "chest", secondary: ["triceps", "front_delts"] },
  { name: "Guillotine Press", primary: "chest", secondary: ["triceps", "front_delts"] },
  { name: "Barbell Upright Row (Wide)", primary: "back", secondary: ["traps", "rear_delts"] },
  { name: "Cable Face Pull (Upper Back)", primary: "back", secondary: ["rear_delts", "traps"] },
  { name: "Smith Machine Row", primary: "back", secondary: ["biceps"] },
  { name: "Half-Kneeling Cable Row", primary: "back", secondary: ["biceps"] },
  { name: "V-Bar Pulldown", primary: "back", secondary: ["biceps"] },
  { name: "Wide-Grip Cable Row", primary: "back", secondary: ["rear_delts"] },
  { name: "Barbell Front Raise", primary: "front_delts", secondary: [] },
  { name: "Plate Front Raise", primary: "front_delts", secondary: [] },
  { name: "Kneeling Dumbbell Press", primary: "front_delts", secondary: ["triceps", "side_delts"] },
  { name: "Single-Arm Dumbbell Press", primary: "front_delts", secondary: ["triceps", "side_delts"] },
  { name: "Half-Kneeling Shoulder Press", primary: "front_delts", secondary: ["triceps", "abs"] },
  { name: "Chin-Up (Supinated)", primary: "biceps", secondary: ["back"] },
  { name: "Seated Dumbbell Curl", primary: "biceps", secondary: [] },
  { name: "Lying Cable Curl", primary: "biceps", secondary: [] },
  { name: "High Cable Curl", primary: "biceps", secondary: [] },
  { name: "Barbell Drag Curl", primary: "biceps", secondary: [] },
  { name: "Smith Machine Close-Grip Press", primary: "triceps", secondary: ["chest"] },
  { name: "Dip Machine", primary: "triceps", secondary: ["chest", "front_delts"] },
  { name: "Cable Kickback (Triceps)", primary: "triceps", secondary: [] },
  { name: "Barbell Skull Crusher", primary: "triceps", secondary: [] },
  { name: "Jefferson Squat", primary: "quads", secondary: ["glutes", "hamstrings"] },
  { name: "Kneeling Squat", primary: "quads", secondary: ["glutes"] },
  { name: "Skater Squat", primary: "quads", secondary: ["glutes"] },
  { name: "Step-Up (Weighted)", primary: "quads", secondary: ["glutes"] },
  { name: "Landmine Squat", primary: "quads", secondary: ["glutes"] },
  { name: "Hip Extension (Cable)", primary: "glutes", secondary: ["hamstrings"] },
  { name: "Stiff-Leg Deadlift (Single-Leg)", primary: "hamstrings", secondary: ["glutes"] },
  { name: "Glute Squeeze Hold", primary: "glutes", secondary: [] },
  { name: "Reverse Lunge (Glute Focus)", primary: "glutes", secondary: ["quads"] },
  { name: "Monster Walk", primary: "glutes", secondary: [] },
  { name: "Agility Ladder Drills", primary: "calves", secondary: ["quads"] },
  { name: "Rope Jump", primary: "calves", secondary: ["quads", "glutes"] },
  { name: "Heel Walk", primary: "tibialis", secondary: [] },
  { name: "Seated Tibialis Raise", primary: "tibialis", secondary: [] },
  { name: "Trap Bar Shrug", primary: "traps", secondary: [] },
  { name: "Cable Upright Row (Traps)", primary: "traps", secondary: ["side_delts", "biceps"] },
  { name: "Dumbbell Pronation/Supination", primary: "forearms", secondary: [] },
  { name: "Gripper Walks", primary: "forearms", secondary: ["traps"] },
  { name: "Landmine Press (Abs)", primary: "abs", secondary: ["front_delts"] },
  { name: "Half-Kneeling Pallof Press", primary: "abs", secondary: [] },
  { name: "Tall-Kneeling Pallof Press", primary: "abs", secondary: [] },
  { name: "GHD Sit-Up", primary: "abs", secondary: ["hamstrings", "glutes"] },
  { name: "Incline Board Sit-Up", primary: "abs", secondary: [] },
  { name: "Hanging Oblique Raise", primary: "abs", secondary: [] },
  { name: "Seated Twist (Plate)", primary: "abs", secondary: [] },
  { name: "Hip Adduction Machine", primary: "adductors", secondary: [] },
  { name: "Cable Hip Adduction", primary: "adductors", secondary: [] },
  { name: "Copenhagen Adduction", primary: "adductors", secondary: ["abs"] },
  { name: "Cossack Squat", primary: "adductors", secondary: ["quads", "glutes"] },
  { name: "Sumo Squat (Adductor Focus)", primary: "adductors", secondary: ["glutes", "quads"] },
  { name: "Side-Lying Adduction", primary: "adductors", secondary: [] },
  { name: "Lateral Lunge", primary: "adductors", secondary: ["quads", "glutes"] },
  { name: "Plate-Loaded Incline Press", primary: "chest", secondary: ["triceps", "front_delts"] },
  { name: "Plate-Loaded Chest Press", primary: "chest", secondary: ["triceps", "front_delts"] },
  { name: "Plate-Loaded Decline Press", primary: "chest", secondary: ["triceps"] },
  { name: "Iso-Lateral Chest Press", primary: "chest", secondary: ["triceps", "front_delts"] },
  { name: "Plate-Loaded Lat Pulldown", primary: "back", secondary: ["biceps"] },
  { name: "Iso-Lateral Front Pulldown", primary: "back", secondary: ["biceps"] },
  { name: "Plate-Loaded Row", primary: "back", secondary: ["biceps", "rear_delts"] },
  { name: "Plate-Loaded High Row", primary: "back", secondary: ["biceps", "rear_delts"] },
  { name: "Plate-Loaded Low Row", primary: "back", secondary: ["biceps"] },
  { name: "Plate-Loaded Shoulder Press", primary: "side_delts", secondary: ["front_delts", "triceps"] },
  { name: "Plate-Loaded Rear Delt", primary: "rear_delts", secondary: ["back"] },
  { name: "Plate-Loaded Preacher Curl", primary: "biceps", secondary: [] },
  { name: "Plate-Loaded Hip Thrust", primary: "glutes", secondary: ["hamstrings"] },
  { name: "Overhead Cable Rope Extension", primary: "triceps", secondary: [] },
  { name: "Plate-Loaded Overhead Extension", primary: "triceps", secondary: [] },
  { name: "Seated Dip Machine", primary: "triceps", secondary: ["chest"] },
  { name: "Lateral Raise Machine", primary: "side_delts", secondary: [] },
  { name: "Preacher Curl Machine", primary: "biceps", secondary: [] },
  { name: "Triceps Extension Machine", primary: "triceps", secondary: [] },
  { name: "Glute Kickback Machine", primary: "glutes", secondary: ["hamstrings"] },
  { name: "Ab Crunch Machine", primary: "abs", secondary: [] },
  { name: "Assisted Dip Machine", primary: "triceps", secondary: ["chest", "front_delts"] },
];
