import { appSchema, tableSchema } from '@nozbe/watermelondb';

export default appSchema({
  version: 1,
  tables: [
    tableSchema({
      name: 'exercises',
      columns: [
        { name: 'server_id', type: 'string', isOptional: true },
        { name: 'user_id', type: 'string', isOptional: true },
        { name: 'name', type: 'string' },
        { name: 'primary_muscle', type: 'string' },
        { name: 'secondary_muscles', type: 'string', isOptional: true },
        { name: 'equipment', type: 'string', isOptional: true },
        { name: 'movement_pattern', type: 'string', isOptional: true },
        { name: 'compound_isolation', type: 'string', isOptional: true },
        { name: 'default_rep_min', type: 'number', isOptional: true },
        { name: 'default_rep_max', type: 'number', isOptional: true },
        { name: 'fatigue_cost', type: 'number', isOptional: true },
        { name: 'stimulus_to_fatigue_ratio', type: 'number', isOptional: true },
        { name: 'is_custom', type: 'boolean' },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'routines',
      columns: [
        { name: 'server_id', type: 'string', isOptional: true },
        { name: 'user_id', type: 'string' },
        { name: 'name', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'split_type', type: 'string', isOptional: true },
        { name: 'is_active', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'routine_exercises',
      columns: [
        { name: 'server_id', type: 'string', isOptional: true },
        { name: 'routine_id', type: 'string', isIndexed: true },
        { name: 'exercise_id', type: 'string', isIndexed: true },
        { name: 'order_in_routine', type: 'number', isOptional: true },
        { name: 'recommended_sets', type: 'number', isOptional: true },
        { name: 'recommended_reps_min', type: 'number', isOptional: true },
        { name: 'recommended_reps_max', type: 'number', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'mesocycles',
      columns: [
        { name: 'server_id', type: 'string', isOptional: true },
        { name: 'user_id', type: 'string' },
        { name: 'name', type: 'string' },
        { name: 'start_date', type: 'string' },
        { name: 'end_date', type: 'string' },
        { name: 'duration_weeks', type: 'number', isOptional: true },
        { name: 'focus', type: 'string', isOptional: true },
        { name: 'goals', type: 'string', isOptional: true },
        { name: 'is_active', type: 'boolean' },
        { name: 'deload_week', type: 'number', isOptional: true },
        { name: 'auto_regulation_enabled', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'workouts',
      columns: [
        { name: 'server_id', type: 'string', isOptional: true },
        { name: 'user_id', type: 'string' },
        { name: 'routine_id', type: 'string', isOptional: true },
        { name: 'mesocycle_id', type: 'string', isOptional: true },
        { name: 'started_at', type: 'number' },
        { name: 'ended_at', type: 'number', isOptional: true },
        { name: 'duration_minutes', type: 'number', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'session_difficulty', type: 'number', isOptional: true },
        { name: 'overall_pump', type: 'number', isOptional: true },
        { name: 'soreness_24h_before', type: 'number', isOptional: true },
        { name: 'fatigue_level', type: 'number', isOptional: true },
        { name: 'is_completed', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'workout_sets',
      columns: [
        { name: 'server_id', type: 'string', isOptional: true },
        { name: 'user_id', type: 'string' },
        { name: 'workout_id', type: 'string', isIndexed: true },
        { name: 'exercise_id', type: 'string', isIndexed: true },
        { name: 'set_number', type: 'number' },
        { name: 'set_type', type: 'string' },
        { name: 'target_reps_min', type: 'number', isOptional: true },
        { name: 'target_reps_max', type: 'number', isOptional: true },
        { name: 'actual_reps', type: 'number' },
        { name: 'weight', type: 'number', isOptional: true },
        { name: 'rir', type: 'number', isOptional: true },
        { name: 'rpe', type: 'number', isOptional: true },
        { name: 'failed', type: 'boolean' },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'post_set_pump', type: 'number', isOptional: true },
        { name: 'post_set_muscle_connection', type: 'number', isOptional: true },
        { name: 'joint_discomfort', type: 'number', isOptional: true },
        { name: 'is_amrap', type: 'boolean' },
        { name: 'amrap_reps', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
  ],
});
