/**
 * Bundled snapshot importers.
 *
 * Two static snapshots ship in the APK and seed the local `foods`
 * cache on first launch:
 *
 *   1. OpenFoodFacts UK  , assets/seed/off_uk_snapshot.dat
 *      Branded UK products. Generated by buildOffSnapshot.js,
 *      refreshed weekly by the GitHub Actions workflow.
 *   2. CoFID UK          , assets/seed/cofid_uk.dat
 *      ~3k generic UK foods (raw chicken breast, plain oats, etc.).
 *      Static dataset, Open Government Licence v3.0.
 *      Generated by buildCofidSnapshot.js.
 *
 * Both share the same on-disk row shape so a single importer handles
 * each. They write into `foods` with their own source label so the
 * waterfall and source-chip taxonomy can tell them apart.
 *
 * .dat extension keeps Metro treating the files as binary assets
 * (numeric registry IDs for Asset.fromModule) instead of inlining
 * the parsed object into the JS bundle. See metro.config.js.
 *
 * Row shape: { ean (or food code), name, brand, serving_g,
 *   kcal_100g, protein_100g, carbs_100g, fat_100g,
 *   fibre_100g?, sodium_100g?, sugar_100g? }
 *
 * Idempotency: per-snapshot AsyncStorage flag keyed by the generated-
 * at timestamp tracks whether THIS version was imported.
 *
 * Failure mode: every error is logged with the boundary it occurred
 * at (asset load / parse / chunk insert / flag write). On any
 * failure the function returns gracefully; the app continues to
 * work with whatever foods are already cached and the live OFF /
 * USDA fallback. No crash, no corruption.
 */
import AsyncStorage from '@react-native-async-storage/async-storage';
import { Asset } from 'expo-asset';
import * as FileSystem from 'expo-file-system/legacy';
import { db, uid } from '../database';
import { logInfo, logWarn, logError } from '../errorLog';

const CHUNK_SIZE = 200;

// ── Snapshot versions (startup fast path) ──────────────────────────
// The authoritative version of each snapshot is `_meta.generatedAt`
// inside the .dat file itself — but reading + JSON.parsing a 6.3 MB
// asset on EVERY launch just to discover "already imported" is a
// multi-hundred-ms JS block. These constants mirror the current
// assets' `_meta.generatedAt` so the version flag can be checked with
// a single AsyncStorage read BEFORE any file I/O.
//
// !! THESE MUST BE BUMPED WHENEVER THE SNAPSHOT ASSETS ARE REGENERATED !!
//   - assets/seed/off_uk_snapshot.dat is rebuilt by
//     scripts/seed/buildOffSnapshot.js (run weekly by
//     .github/workflows/refresh-off-snapshot.yml, which bumps
//     OFF_SNAPSHOT_VERSION from the new `_meta.generatedAt` in the
//     same commit).
//   - assets/seed/cofid_uk.dat is rebuilt by
//     scripts/seed/buildCofidSnapshot.js (static dataset, rare).
//
// A stale constant is NOT harmless (hostile review, Wave 1): a user
// whose stored flag equals the stale constant takes the fast path and
// the authoritative post-parse check never runs, so a regenerated
// asset is silently never imported for existing users. The workflow
// bump above plus the constant-vs-asset drift guard in
// seed.versionSkip.test.js (red in CI on divergence) are what keep
// this safe. A stale constant only degrades to safe-but-slow for
// users whose stored flag differs from it (fresh installs re-import
// correctly either way).
// Exported for the fast-path regression test (seed.versionSkip.test.js).
export const OFF_SNAPSHOT_VERSION = "2026-07-05T07:42:27.991Z";
export const COFID_SNAPSHOT_VERSION = '2026-05-25T06:02:02.491Z';

const _inFlight = new Map();

// SQLite gives us one connection shared across the app. Two importers
// firing from RootNavigator bootstrap will both try to BEGIN on it
// concurrently, which expo-sqlite rejects ("cannot start a transaction
// within a transaction"). Serialise every transaction-scoped block
// through this mutex so the second importer's chunks queue cleanly
// behind the first.
let _txMutex = Promise.resolve();
function _withTxLock(fn) {
  const next = _txMutex.then(() => fn(), () => fn());
  _txMutex = next.then(() => {}, () => {});
  return next;
}

/**
 * OFF UK snapshot importer (branded products, ~100k+ rows).
 */
export function importOffSnapshotIfNeeded() {
  return _importIfNeeded({
    scopeKey: 'off',
    flagKey: '@volyume_off_snapshot_loaded_v1',
    expectedVersion: OFF_SNAPSHOT_VERSION,
    sourceLabel: 'off',
    loadModule: () => require('../../../assets/seed/off_uk_snapshot.dat'),
  });
}

/**
 * CoFID UK snapshot importer (generic foods, ~3k rows).
 */
export function importCofidSnapshotIfNeeded() {
  return _importIfNeeded({
    scopeKey: 'cofid',
    flagKey: '@volyume_cofid_snapshot_loaded_v1',
    expectedVersion: COFID_SNAPSHOT_VERSION,
    sourceLabel: 'cofid',
    loadModule: () => require('../../../assets/seed/cofid_uk.dat'),
  });
}

function _importIfNeeded(spec) {
  if (_inFlight.has(spec.scopeKey)) return _inFlight.get(spec.scopeKey);
  const p = _run(spec).finally(() => { _inFlight.delete(spec.scopeKey); });
  _inFlight.set(spec.scopeKey, p);
  return p;
}

async function _run({ scopeKey, flagKey, expectedVersion, sourceLabel, loadModule }) {
  const t0 = Date.now();
  let meta = null;
  let rows = null;

  // ── 0. Fast-path version check ────────────────────────────────────
  // One AsyncStorage read BEFORE any file I/O. On every launch after a
  // successful import this is the only work done — the 6.3 MB read +
  // JSON.parse below never runs. If the constant is stale (asset
  // regenerated without a bump) this check simply misses and the
  // authoritative post-parse check in step 2 takes over.
  try {
    const lastImportedFast = await AsyncStorage.getItem(flagKey);
    if (lastImportedFast != null && lastImportedFast === expectedVersion) {
      logInfo(`food.seed.${scopeKey}.skip`, `snapshot version ${expectedVersion} already imported`);
      return { ok: true, reason: 'already_loaded', importedRows: 0 };
    }
  } catch (_) { /* tolerate -- fall through to the full path */ }

  // ── 1. Load the bundled asset ─────────────────────────────────────
  try {
    const moduleRef = loadModule();
    if (typeof moduleRef !== 'number') {
      logError(`food.seed.${scopeKey}.asset.type`, new Error('require did not return an asset id'), {
        type: typeof moduleRef,
        hint: 'Metro likely not configured to treat .dat as asset; check metro.config.js',
      });
      return { ok: false, reason: 'asset_not_registered', importedRows: 0 };
    }
    const asset = Asset.fromModule(moduleRef);
    await asset.downloadAsync();
    const uri = asset.localUri || asset.uri;
    if (!uri) {
      logWarn(`food.seed.${scopeKey}.asset.noUri`, 'snapshot asset has no local URI', {});
      return { ok: false, reason: 'no_uri', importedRows: 0 };
    }
    const raw = await FileSystem.readAsStringAsync(uri);
    const parsed = JSON.parse(raw);
    meta = parsed?._meta ?? null;
    rows = Array.isArray(parsed?.rows) ? parsed.rows : null;
    if (!rows) {
      logWarn(`food.seed.${scopeKey}.parse.noRows`, 'snapshot parsed but rows missing', { meta });
      return { ok: false, reason: 'no_rows', importedRows: 0 };
    }
  } catch (e) {
    logError(`food.seed.${scopeKey}.load`, e, { message: e?.message });
    return { ok: false, reason: 'load_failed', importedRows: 0 };
  }

  // Placeholder snapshot (rows == 0) is a successful no-op. Logged at
  // info so the dashboard shows the build went out without a real
  // snapshot but it isn't an error, live fallback covers it.
  if (rows.length === 0) {
    logInfo(`food.seed.${scopeKey}.placeholder`,
      `snapshot is the placeholder (rowCount=0, generatedAt=${meta?.generatedAt ?? 'unknown'}).`);
    return { ok: true, reason: 'placeholder', importedRows: 0 };
  }

  // ── 2. Check the version flag ─────────────────────────────────────
  const version = String(meta?.generatedAt ?? meta?.version ?? '1');
  let lastImported = null;
  try {
    lastImported = await AsyncStorage.getItem(flagKey);
  } catch (_) { /* tolerate -- treat as never imported */ }

  if (lastImported === version) {
    logInfo(`food.seed.${scopeKey}.skip`, `snapshot version ${version} already imported`);
    return { ok: true, reason: 'already_loaded', importedRows: 0 };
  }

  // ── 3. Import in chunks ──────────────────────────────────────────
  logInfo(`food.seed.${scopeKey}.import.start`,
    `importing ${rows.length} rows from ${sourceLabel} snapshot ${version}`);

  let d;
  try {
    d = await db();
  } catch (e) {
    logError(`food.seed.${scopeKey}.dbOpen`, e, { message: e?.message });
    return { ok: false, reason: 'db_open_failed', importedRows: 0 };
  }

  let importedRows = 0;
  let skippedRows = 0;
  const now = Date.now();

  for (let i = 0; i < rows.length; i += CHUNK_SIZE) {
    const chunk = rows.slice(i, i + CHUNK_SIZE);
    const result = await _withTxLock(async () => {
      let inTx = false;
      try {
        await d.execAsync('BEGIN');
        inTx = true;
        let imp = 0;
        let skp = 0;
        for (const row of chunk) {
          if (!_isUsableRow(row)) {
            skp++;
            continue;
          }
          try {
            // CoFID rows reuse the `ean` field for the food code
            // ("13-145"); they have no real barcode, so barcode_ean
            // stays null and only source_id carries the identifier.
            const sourceId = row.ean ?? null;
            const barcodeEan = sourceLabel === 'off' ? (row.ean ?? null) : null;
            await d.runAsync(
              `INSERT OR IGNORE INTO foods
                (id, source, source_id, barcode_ean, name, brand,
                 serving_g, serving_label,
                 kcal_100g, protein_100g, carbs_100g, fat_100g, fibre_100g,
                 sodium_100g, sugar_100g,
                 verified, fetched_at, created_at, updated_at)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
              [
                uid(), sourceLabel, sourceId, barcodeEan,
                row.name ?? 'Unknown', row.brand ?? null,
                _num(row.serving_g) ?? 100, row.serving_label ?? null,
                _num(row.kcal_100g), _num(row.protein_100g),
                _num(row.carbs_100g), _num(row.fat_100g),
                _num(row.fibre_100g), _num(row.sodium_100g), _num(row.sugar_100g),
                0, now, now, now,
              ]
            );
            imp++;
          } catch (_rowErr) {
            skp++;
          }
        }
        await d.execAsync('COMMIT');
        inTx = false;
        return { imp, skp };
      } catch (chunkErr) {
        if (inTx) {
          try { await d.execAsync('ROLLBACK'); } catch (_) { /* tolerate */ }
        }
        logError(`food.seed.${scopeKey}.chunk`, chunkErr, {
          chunkStart: i, chunkSize: chunk.length,
          message: chunkErr?.message,
        });
        return { imp: 0, skp: 0 };
      }
    });
    importedRows += result.imp;
    skippedRows += result.skp;
  }

  // ── 4. Persist the version flag ───────────────────────────────────
  try {
    await AsyncStorage.setItem(flagKey, version);
  } catch (e) {
    logWarn(`food.seed.${scopeKey}.flag.persist`, e?.message ?? 'unknown', { version });
  }

  const ms = Date.now() - t0;
  logInfo(`food.seed.${scopeKey}.import.done`,
    `imported=${importedRows} skipped=${skippedRows} ms=${ms} version=${version}`);

  return {
    ok: true,
    reason: 'imported',
    importedRows,
    skippedRows,
    ms,
    version,
  };
}

function _isUsableRow(row) {
  return row
    && typeof row.name === 'string'
    && _num(row.kcal_100g) != null
    && _num(row.protein_100g) != null
    && _num(row.carbs_100g) != null
    && _num(row.fat_100g) != null;
}

function _num(v) {
  if (v == null) return null;
  const n = typeof v === 'string' ? parseFloat(v) : v;
  return Number.isFinite(n) ? n : null;
}
