/**
 * Bundled OpenFoodFacts UK snapshot importer.
 *
 * On first launch, copies the UK products snapshot shipped with the
 * APK into the local `foods` table. After that, the existing
 * waterfall (localCache -> liveOff -> usda) finds them as cache hits
 * with no network.
 *
 * Source data: assets/seed/off_uk_snapshot.dat
 *   Generated by `scripts/seed/buildOffSnapshot.js` at build time.
 *   File contains a JSON document; .dat extension keeps Metro treating
 *   it as a binary asset (numeric registry ID for Asset.fromModule)
 *   instead of inlining the parsed object into the JS bundle.
 *   Shape: { _meta: {...}, rows: [{ ean, name, brand, serving_g,
 *           kcal_100g, protein_100g, carbs_100g, fat_100g,
 *           fibre_100g?, sodium_100g?, sugar_100g? }] }
 *
 * Idempotency: an AsyncStorage flag keyed by the snapshot's
 * generated-at timestamp tracks whether THIS snapshot version was
 * imported. A new snapshot (newer generatedAt) will be re-imported;
 * an unchanged snapshot is skipped.
 *
 * Failure mode: every error is logged with the boundary it occurred
 * at (asset load / parse / chunk insert / flag write). On any
 * failure the function returns gracefully; the app continues to
 * work with whatever foods are already in the local cache and the
 * live OFF/USDA fallback. No crash. No corruption (failed inserts
 * are wrapped per-chunk, partial progress is preserved).
 */
import AsyncStorage from '@react-native-async-storage/async-storage';
import { Asset } from 'expo-asset';
import * as FileSystem from 'expo-file-system';
import { db, uid } from '../database';
import { logInfo, logWarn, logError } from '../errorLog';

const FLAG_KEY = '@volyume_off_snapshot_loaded_v1';
const CHUNK_SIZE = 200;
const SOURCE_LABEL = 'off';

let _inFlight = null;

/**
 * Idempotent. Calls multiplex into a single in-flight promise so
 * concurrent callers (e.g. boot sequence + first scan) share one
 * import run rather than racing each other.
 */
export async function importOffSnapshotIfNeeded() {
  if (_inFlight) return _inFlight;
  _inFlight = _run().finally(() => { _inFlight = null; });
  return _inFlight;
}

async function _run() {
  const t0 = Date.now();
  let meta = null;
  let rows = null;

  // ── 1. Load the bundled asset ─────────────────────────────────────
  try {
    // eslint-disable-next-line global-require
    const moduleRef = require('../../../assets/seed/off_uk_snapshot.dat');
    if (typeof moduleRef !== 'number') {
      logError('food.seed.asset.type', new Error('require did not return an asset id'), {
        type: typeof moduleRef,
        hint: 'Metro likely not configured to treat .dat as asset; check metro.config.js',
      });
      return { ok: false, reason: 'asset_not_registered', importedRows: 0 };
    }
    const asset = Asset.fromModule(moduleRef);
    await asset.downloadAsync();
    const uri = asset.localUri || asset.uri;
    if (!uri) {
      logWarn('food.seed.asset.noUri', 'snapshot asset has no local URI', {});
      return { ok: false, reason: 'no_uri', importedRows: 0 };
    }
    const raw = await FileSystem.readAsStringAsync(uri);
    const parsed = JSON.parse(raw);
    meta = parsed?._meta ?? null;
    rows = Array.isArray(parsed?.rows) ? parsed.rows : null;
    if (!rows) {
      logWarn('food.seed.parse.noRows', 'snapshot parsed but rows missing', { meta });
      return { ok: false, reason: 'no_rows', importedRows: 0 };
    }
  } catch (e) {
    logError('food.seed.load', e, { message: e?.message });
    return { ok: false, reason: 'load_failed', importedRows: 0 };
  }

  // Placeholder snapshot (rows == 0) is a successful no-op. Logged at
  // info so the dashboard shows the build went out without a real
  // snapshot but it isn't an error -- the live fallback covers it.
  if (rows.length === 0) {
    logInfo('food.seed.placeholder',
      `snapshot is the placeholder (rowCount=0, generatedAt=${meta?.generatedAt ?? 'unknown'}). Live OFF/USDA cover lookups.`);
    return { ok: true, reason: 'placeholder', importedRows: 0 };
  }

  // ── 2. Check the version flag ─────────────────────────────────────
  const version = String(meta?.generatedAt ?? meta?.version ?? '1');
  let lastImported = null;
  try {
    lastImported = await AsyncStorage.getItem(FLAG_KEY);
  } catch (_) { /* tolerate -- treat as never imported */ }

  if (lastImported === version) {
    logInfo('food.seed.skip', `snapshot version ${version} already imported`);
    return { ok: true, reason: 'already_loaded', importedRows: 0 };
  }

  // ── 3. Import in chunks ──────────────────────────────────────────
  logInfo('food.seed.import.start',
    `importing ${rows.length} rows from snapshot ${version}`);

  let d;
  try {
    d = await db();
  } catch (e) {
    logError('food.seed.dbOpen', e, { message: e?.message });
    return { ok: false, reason: 'db_open_failed', importedRows: 0 };
  }

  let importedRows = 0;
  let skippedRows = 0;
  const now = Date.now();

  for (let i = 0; i < rows.length; i += CHUNK_SIZE) {
    const chunk = rows.slice(i, i + CHUNK_SIZE);
    try {
      // Wrap each chunk in a transaction so a single bad row only
      // costs that row, not the whole chunk. The chunk's other rows
      // still land. If the whole chunk fails (transaction abort),
      // we log + move on to the next chunk.
      await d.execAsync('BEGIN');
      for (const row of chunk) {
        if (!_isUsableRow(row)) {
          skippedRows++;
          continue;
        }
        try {
          await d.runAsync(
            `INSERT OR IGNORE INTO foods
              (id, source, source_id, barcode_ean, name, brand,
               serving_g, serving_label,
               kcal_100g, protein_100g, carbs_100g, fat_100g, fibre_100g,
               sodium_100g, sugar_100g,
               verified, fetched_at, created_at, updated_at)
             VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
            [
              uid(), SOURCE_LABEL, row.ean ?? null, row.ean ?? null,
              row.name ?? 'Unknown', row.brand ?? null,
              _num(row.serving_g) ?? 100, row.serving_label ?? null,
              _num(row.kcal_100g), _num(row.protein_100g),
              _num(row.carbs_100g), _num(row.fat_100g),
              _num(row.fibre_100g), _num(row.sodium_100g), _num(row.sugar_100g),
              0, now, now, now,
            ]
          );
          importedRows++;
        } catch (rowErr) {
          // One bad row -- keep going. The transaction will commit
          // the rest.
          skippedRows++;
          // Don't log per row to avoid Sentry/log blow-up. The
          // skipped count surfaces in the final log line.
        }
      }
      await d.execAsync('COMMIT');
    } catch (chunkErr) {
      try { await d.execAsync('ROLLBACK'); } catch (_) { /* tolerate */ }
      logError('food.seed.chunk', chunkErr, {
        chunkStart: i, chunkSize: chunk.length,
        message: chunkErr?.message,
      });
      // Continue to the next chunk -- partial import is still a win.
    }
  }

  // ── 4. Persist the version flag ───────────────────────────────────
  try {
    await AsyncStorage.setItem(FLAG_KEY, version);
  } catch (e) {
    logWarn('food.seed.flag.persist', e?.message ?? 'unknown', { version });
    // Flag failed to persist; next launch will re-run the import.
    // INSERT OR IGNORE makes that safe (no duplicates).
  }

  const ms = Date.now() - t0;
  logInfo('food.seed.import.done',
    `imported=${importedRows} skipped=${skippedRows} ms=${ms} version=${version}`);

  return {
    ok: true,
    reason: 'imported',
    importedRows,
    skippedRows,
    ms,
    version,
  };
}

function _isUsableRow(row) {
  return row
    && typeof row.name === 'string'
    && _num(row.kcal_100g) != null
    && _num(row.protein_100g) != null
    && _num(row.carbs_100g) != null
    && _num(row.fat_100g) != null;
}

function _num(v) {
  if (v == null) return null;
  const n = typeof v === 'string' ? parseFloat(v) : v;
  return Number.isFinite(n) ? n : null;
}
